### ISSUE TITLE
Update of a package recipe?

### ISSUE THREAD

**Issue by davidechicco** [bioconda/bioconda-recipes#11102]
Hi
I just updated the recipe of my project BEHST, to the 3.5 version. I think everything went well ([here's the pull request](https://github.com/bioconda/bioconda-recipes/pull/11101)), but I just tried to install BEHST on a new computer (`conda install behst`), and it downloaded the former version (not the 3.5 one). Why? Did I forget some step for the update procedure?

I also noticed that [Anaconda](https://anaconda.org/bioconda/behst) lists the former version of BEHST. How can I propagate my update correctly there too? 

Please let me know if I'm missing something in this package recipe update procedure.

Thanks

-- Davide

**Comment by eseiler** [comment]
Hey @davidechicco,

BEHST is currently blacklisted:
https://github.com/bioconda/bioconda-recipes/blob/01c59a026a9b1da00fc52b4cb5aa32f660e3ff89/build-fail-blacklist#L1739-L1740

So you need to remove the blacklisting. If everything works, it will also be uploaded.
(You probably don't need to increase the build number of the BEHST recipe, since it was never built)

**Comment by davidechicco** [comment]
Hi @eseiler 
Thanks for the information. How can I remove the blacklisting?

-- Davide

**Comment by davidechicco** [comment]
Hi @eseiler 
I tried to remove BEHST from the backlist, and pulled the changes. I hope I did everything correctly.

Please let me know your feedback about the situation as soon as you have time.

Thanks

-- Davide

**Comment by eseiler** [comment]
Looks good now and also pops up when running `conda search behst` :)
