### ISSUE TITLE
recipe is not built

### ISSUE THREAD

**Issue by cjandrasits** [bioconda/bioconda-recipes#11615]
Hi,

I updated my recipe with a new version.
I upped the version (1.0.0 to 1.0.1) and build number (1 to 2) in the meta.yml (PR #11613 and PR #11614 ).
As the test did not fail, I merged it - however I now realized that my recipe was not rebuilt in either of the PRs:
https://circleci.com/gh/bioconda/bioconda-recipes/31171
'''
07:32:53 BIOCONDA INFO Nothing to be done for recipe recipes/seq-seq-pan
'''

What do I need to do to have my recipe built?!

Thanks,
Christine

**Comment by rekm** [comment]
Hi, 

I was able to reproduce the behaviour running the following command

    bioconda-utils build recipes/seq-seq-pan config.yaml

1. The  top level meta.yaml and build.sh get ignored every time  
and only the recipes in the version sub-folders gets processed. 
2. conda build 3 trips over your build skip [ osx or py27]
likely due to its new fancy host recipe field.
 
**Adding python as host dependency fixes the Issue.
requirements:/host:/- python**

It also sees 1.0.1 if you remove your build skip (would not recommend doing that)

Why only 1.0.1? Because 1.0.0  already exists in one of the channels bioconda-utils checks against.    

Following setup: 

Debian GNU/Linux 9.5 , miniconda3  
conda_build_config.yaml (stolen from conda-forge repository and stashed away in root environment) 
conda 4.5.11, conda-build 3.16.2, bioconda-utils 0.14.9
build_config.yaml 
recipe_repo
+   recipes
     + seq-seq-pan
         + meta.yaml (1.0.1)
         + build.sh (1.0.1) 
         +  1.0.0
              + meta.yaml
              + build.sh 
         +  1.0.1
              + meta.yaml
              + build.sh 
+ config.yaml (stolen from this repository) 
                    
 Hope this is decent first step

**Comment by cjandrasits** [comment]
Thank you!! adding host: -python solved the issue :smile:
