### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#124]
Hi,
I wonder if we should let builds fail if there is no test case implemented. This way, we could "make sure" that we e.g. don't forget to copy the bins or set the right permissions to wrapper scripts.

What do you think?

**Comment by daler** [comment]
Sounds good. I don't think meta-packages would be problematic, since they could just have a dummy test case (`ls` or something) if there's nothing to actually test.

**Comment by johanneskoester** [comment]
We should also check if the recipe has a summary. Any other things that should be mandatory?

**Comment by daler** [comment]
`about/license` should probably be mandatory. It will at least make recipe creators check whether or not tools can be redistributed. 

[This part](http://conda.pydata.org/docs/building/meta-yaml.html#license-file) of the conda docs points out that many licenses require a copy be distributed. Maybe we could just set `license_file: True` on all recipes? 

`about/home` should be required so that it's easy to find original authors.

**Comment by tomkinsc** [comment]
Perhaps we should require the hash for external dependencies, via `source/{md5, sha1, sha256}`. Pinning recipes to a particular version helps ensure packages behave as expected, but requiring a hash would help ensure the packages themselves have not changed or been tampered with. Bioconda should be a trusted channel, and enforcing hashes would help. We cannot guarantee that packages sourced from third parties are the same, but we can at least cause builds to fail if they differ. It looks like most (all?) recipes currently include a hash, so making it required shouldn't be much work if we're already planning to inspect for test cases, license, etc.

**Comment by dkoppstein** [comment]
> Any other things that should be mandatory?

I put 

    extra:
      maintainers: 
        - David Koppstein <davidkoppstein@abvitro.com>

in my included recipe, perhaps it would be good practice to do the same generally. 

>Perhaps we should require the hash for external dependencies

I agree with this.

**Comment by johanneskoester** [comment]
The thing with maintainers is that it kind of could make people think that they become responsible for a package once having added it. This could generate quite some workload for those who have added a lot of dependencies. What do you think?

**Comment by daler** [comment]
Who *is* responsible for a package after adding it? I guess the answer would be anyone who uses the package via conda. In that case, I think the barrier for a user to contribute a fix, update, or whatever should be as low as possible. Seeing someone as the maintainer would raise the barrier for me because I'd think 1) I'd have to clear any changes with them ahead of time and 2) if they're the maintainer they probably know a lot more about it than me; my idea is probably dumb if they haven't already done it.

So adding a maintainer could raise the barrier for initial commits (due to perceived future responsibility) as well as for fixes/patches/updates (due to not wanting to step on anyone's toes).

If adding a maintainer is more about "who to ask" rather than "who is responsible", then as David mentioned git blame does that just fine, and with more granularity.

Of course, having no maintainer makes it all the more important to have tests that tell us if something's broken.

**Comment by johanneskoester** [comment]
I think I agree with your points about the maintainer.

**Comment by johanneskoester** [comment]
However, there might be cases where some of us **want** to be asked, for example, if the recipe is for one of our own tools?

**Comment by daler** [comment]
Good point. For those cases, can we somehow make it more obvious? How about a `protected-recipes` subdirectory, where each recipe is required to have a maintainer, and that maintainer should be consulted before changes are made?

**Comment by dkoppstein** [comment]
Hi, I think I'm convinced that having the creator of the package as the maintainer could lead to unbalanced workloads. On the flip side, I could imagine packages might go out of date often and/or submitted issues might go unresolved if it's unclear who's responsible, which might lead to bioconda being viewed as an unreliable channel. I think it's too early to tell whether this will be an issue and I don't have any experience as a package maintainer, though, so I think it's fine not to have a dedicated maintainer for each package for now. 

I just wanted to point to some resources I found on how other community-based package management systems work, for example the [FreeBSD port maintainer's handbook](https://www.freebsd.org/doc/en_US.ISO8859-1/articles/contributing/ports-contributing.html#maintain-port) which assumes a great deal of responsibility for a package's maintainer, to e.g. [homebrew](https://github.com/Homebrew/homebrew/blob/master/CONTRIBUTING.md), which seems to be more laissez-faire. Maybe @hyeshik has some input since he was on the FreeBSD team?

**Comment by bgruening** [comment]
Yes!!! Packages without a test should fail. See this one: https://github.com/bioconda/bioconda-recipes/issues/2276

Imho this should part of linting and bioconda-utils. Marking for the hackathon.

**Comment by bgruening** [comment]
This should be implemented in bioconda-utils - and we should consider meta-packages. I would argue that meta-packages also can add one simple test, but there was a discussion recently and not everyone agreed.

**Comment by daler** [comment]
closed via https://github.com/bioconda/bioconda-utils/pull/57
