### ISSUE TITLE
biom-format and Python 3 support

### ISSUE THREAD

**Issue by wasade** [bioconda/bioconda-recipes#1310]
biom-format 2.1.5 supports Python 3.4 and 3.5, but the py3 builds are not available within bioconda. I suspect this is because the dependency stack for py3 differs. Notably, the Python 2 package `pyqi` is not part of the biom-format py3 build. Is it possible to specify Python version specific dependencies? I apologize if this is a trivial thing, I'm not very familiar with what can be done in `meta.yaml` and I didn't see a means with a quick google search.

**Comment by johanneskoester** [comment]
Thanks for reporting! Indeed, it is possible to specify dependencies for python3 that differ from python2. @bgruening any interest/time in taking this over, since you posted the package? We should add to our guidelines that Python 3 versions should be generated if possible. I don't want bioconda to slow down this **much** needed transition.

**Comment by wasade** [comment]
Ah, fantastic! 

@bgruening, I'd be glad to help if needed.

**Comment by bgruening** [comment]
@wasade sure. Any other difference between the py2k and py3k builds besides pyqi?

**Comment by wasade** [comment]
Shouldn't be. We do docs via Sphinx off the 2.7 build, but that isn't pertinent here afaik. Travis config [here](https://github.com/biocore/biom-format/blob/master/.travis.yml).

**Comment by bgruening** [comment]
@wasade have a look at this PR: https://github.com/bioconda/bioconda-recipes/pull/1313

**Comment by bgruening** [comment]
Done!

**Comment by wasade** [comment]
Thanks!!
