### ISSUE TITLE
Trinity package issues

### ISSUE THREAD

**Issue by yesimon** [bioconda/bioconda-recipes#1312]
@tomkinsc We have an older version of trinity - 2011_11_26, which I believe is overriding the default latest versions in the 2.* series based on trinity version numbering. We need to figure out a new numbering for one-offs, perhaps something like `date.2011.11.26`, which should work nicely without resorting to an epoch change.

Secondly I believe the OS X version of trinity in the `2.*` series is outright broken due to not actually building the core binaries and these packages should be scrubbed from the conda channel. To remedy this I've managed to build a clang only package in the `yesimon` channel, but with no OpenMP speedups via Parafly because it would be non-native.

**Comment by tomkinsc** [comment]
The "`date.`" prefix sounds good, and the ordering checks out OK via [conda/conda/version.py](https://github.com/conda/conda/blob/master/conda/version.py). It's in PR #1315.

w/r/t the `2.*` version on OSX: builds for OSX are currently skipped. If you can alter the current recipe to add your clang-only build for OSX, it would be better than having no Mac builds. If we can preserve the current linux build with OpenMP, we should.

Paging @abretaud, since you've worked on the recipe for the `2.*` version.

**Comment by abretaud** [comment]
It looks good! I don't have an OSX machine to test, so I totally trust you!

**Comment by dpark01** [comment]
I think this works fine now, can this be closed?

**Comment by abretaud** [comment]
Yes! (for me at least)

**Comment by dpark01** [comment]
@yesimon or @tomkinsc can you close this issue?
