### ISSUE TITLE
big files in recipes

### ISSUE THREAD

**Issue by lpantano** [bioconda/bioconda-recipes#1356]
Hi,

I am getting this warning: 

```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File recipes/group_humann2_uniref_abundances_to_go/test-data/map_infogo1000_uniref50_02_22_2016.txt is 64.67 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

Do we want to add big files in the recipes?

**Comment by chapmanb** [comment]
+1 It would be great to avoid these huge files within the git repo. The git clone is currently pretty heavy.

**Comment by kyleabeauchamp** [comment]
Github large file storage is an option.  In the past, I've also used figshare to get DOI-numbered (e.g. citable) dataset storage.  See e.g. https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/example_datasets/alanine_dipeptide.py

**Comment by daler** [comment]
Looking at the `group_humann2_uniref_abundances_to_go` [`meta.yaml`](https://github.com/bioconda/bioconda-recipes/blob/c4410c5ad3055010e7a572c6421608e4deb6fe3d/recipes/group_humann2_uniref_abundances_to_go/meta.yaml) file, the 111MB of files in question come from the downloaded github release. Then they are used for testing correctness of the `group_humann2_uniref_abundances_to_GO.sh` script in the `meta.yaml`.

@bebatut are the `test-data` files needed for the script to function? If not, then the `test-data` dir should be removed from the recipe, since here we only care that the program runs and leave the full unit testing to the developers (see [guidelines' section on testing](https://github.com/bioconda/bioconda-recipes/blob/master/GUIDELINES.md#tests)).

If you really do need the files to test correct installation -- which may be the case here, since it's calling python scripts -- then you could write a `test.sh` that downloads the git repo and extracts the test data 
(see [conda docs](http://conda.pydata.org/docs/building/meta-yaml.html#test-section) on that), runs your existing tests, and then cleans up afterwards. That way the data aren't stored in the recipe itself.

In addition you can provide a script to download the test data after the package has been installed. I ended up doing this in the [Spectacle recipe](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/spectacle).

Moving forward, we should be on the lookout for these large-file commits. Even after being deleted, they're still retained in the history so the git clone takes just as long. There are fixes, but it's easier to avoid in the first place.

**Comment by bebatut** [comment]
My bad, I did not see the warning
I will remove the `test-data`

**Comment by daler** [comment]
Great, thanks!
