### ISSUE TITLE
Usage of r- and bioconductor- prefix for packages

### ISSUE THREAD

**Issue by pcm32** [bioconda/bioconda-recipes#13589]
Currently we might be misusing the `r-` and `bioconda-`. We have packages called (r-|bioconductor-)<tool>-<scripts> inside bioconda, however they are not proper R packages, but just providing R scripts so that the functionality of that tool is exposed to the shell. Since they have the r- prefix they get blacklisted every now and then (I presume prior to R version changes). We want to rename those packages by removing the initial r- prefix. Is there a procedure established for moving/renaming recipes? Or any recommended way of doing it? Couldn't find anything in the docs. 

Should we have more strict requisites on the usage of these prefixes?

**Comment by pcm32** [comment]
Regarding renaming recipes, I would just create a new recipe and copy contents over. Not sure how to deprecate the previous recipe? Just by deleting it from the repo? Let me know.

**Comment by nsoranzo** [comment]
`git mv recipes/r-foo/ recipes/foo` ?

**Comment by dpryan79** [comment]
I would propose essentially as @nsoranzo mentioned. Namely, upon the next release of any of those scripts, `git mv` to remove the `r-` or `bioconductor-` prefix and also change the package name in the `meta.yaml` to remove the aforementioned prefix. We should then remove the entry from the blacklist, since it's no longer applicable to anything.

**Comment by dpryan79** [comment]
We should also see if there are any packages using these scripts as dependencies and update them accordingly.

**Comment by bgruening** [comment]
@pcm32 this can be closed now, isn't it?

**Comment by pcm32** [comment]
Thanks, yes
