### ISSUE TITLE
Use old c compiler instead of GCC7

### ISSUE THREAD

**Issue by shunhuahan** [bioconda/bioconda-recipes#14067]
- I'm trying to compile MEME 4.8.1 which requires old gcc compiler and library (like gcc-4.8.5) to get all MEME utilities to work properly.
- Since bioconda GCC7 migration is recently finished, I used the following way to use old gcc compiler and library in `meta.yaml`. However, the gcc library doesn't seem to be recognized properly during `circleci build`. I get the feeling that I have to specifically export the library path in `build.sh`, but nothing seems to work right now. Do anyone has suggestions or experience on this issue? Thanks!
```
requirements:
  build:
    - gcc=4.8.5
    - libgcc=4.8.5
```

**Comment by molpopgen** [comment]
Why does the package require an older compiler?  Typically, this is a sign that the code needs some updating--newer GCC versions are much better at finding standards violations, etc..

I think you may need `==` instead of `=` to pin versions.   Also, libgcc will be a `run` dependency as well as a `build` dependency.

**Comment by PertuyF** [comment]
@shunhuahan Looks like this version was added to Bioconda 5 days ago (see #14017 ).

**Comment by epruesse** [comment]
Thanks @PertuyF and @shunhuahan
