### ISSUE TITLE
A bioconda-utils module

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#1463]
It would be nice to have a general `bioconda-utils` module where all the infrastructure code could live to avoid overlap. Perhaps this issue can be a place to pool ideas. Here's a start:

`bioconda-utils` as the main command-line interface

Replace the existing `build-packages.py` with `bioconda-utils build`

Add a `bioconda-utils test` for stuff in #1402

`bioconda-utils bioconductor` can replace the Bioconductor helper scripts

`bioconda-utils ucsc` can replace the UCSC helper scripts

`bioconda-utils skeleton` to create a starting point for new recipes.  `bioconda-utils skeleton perl` should add `perl-threaded` as a dependency.  Depending on how the gcc/llvm situation resolves, `gcc #[linux]` and `llvm [#osx]` can be included with `bioconda-utils skeleton c`. `bioconda-utils skeleton pip` can just call the standard `conda skeleton pip`, same for R packages. Might as well have a `bioconda-utils skeleton bioconductor` too.

`bioconda-utils draw` for showing the DAG of recipes

Include a linter for recipes to make sure license and checksums are included in new recipes (xref #162).

@bioconda/all, any other things you'd like to have?

**Comment by chapmanb** [comment]
Ryan -- this sounds so great. Thanks for organizing all the scripts like this.

**Comment by johanneskoester** [comment]
Perfect, that's exactly what we need!  

  

  

On May 4 2016, at 3:40 am, Brad Chapman &lt;notifications@github.com&gt;
wrote:  

> Ryan -- this sounds so great. Thanks for organizing all the scripts like
this.

>

> —  
You are receiving this because you are on a team that was mentioned.  
Reply to this email directly or [view it on
GitHub](https://github.com/bioconda/bioconda-recipes/issues/1463#issuecomment-
216717834)![](https://github.com/notifications/beacon
/ABxcVkM1ZQTwF5OXyWWztPFGWGzAr-jCks5p9_kOgaJpZM4IWUtB.gif)

**Comment by bgruening** [comment]
@daler is rocking this already. So I close this issue now.
