### ISSUE TITLE
Cannot install happer package

### ISSUE THREAD

**Issue by standage** [bioconda/bioconda-recipes#15072]
The happer package was merged yesterday in #15039, but it is still inaccessible (cannot `conda install`). It should be accessible by now, correct?

**Comment by standage** [comment]
cc @bioconda/core

**Comment by epruesse** [comment]
Did you self merge...
You called the package microhabdb

**Comment by epruesse** [comment]
@bgruening See https://anaconda.org/bioconda/microhapdb/files - I think that file needs to be deleted ASAP.

**Comment by epruesse** [comment]
And the container removed.

**Comment by dpryan79** [comment]
Should all builds be removed? I can remove the packages at least, I just need to know if all of them should go.

**Comment by epruesse** [comment]
No, just the 0.1.1

**Comment by dpryan79** [comment]
Ah, I just looked at the PR. As you said @epruesse, I'll remove 0.1.1.

**Comment by dpryan79** [comment]
They should be cleared out of the cache in ~20 minutes. @bgruening Can you delete the container sometime?

**Comment by bgruening** [comment]
Someone was faster ;) Container is removed.
We could add a test that checks if the folder name is equal to the package name to prevent such copy and paste mistakes.

**Comment by epruesse** [comment]
It was me - figured it would be best to do it ASAP.

See ticket - same thought. This isn't the first time.

**Comment by standage** [comment]
Thanks everyone. Is it considered bad form to merge your own pull requests?

**Comment by epruesse** [comment]
The usual way /core talks about it is "well, we are guilty of it ourselves".

**Comment by epruesse** [comment]
Just think of it as writing a check or filling in an online money transfer. You want to double check before you sign or click on go. Just in case. And so having a second person look it over helps prevent mistakes.

Taking packages "back" works only in the very short term. As soon as it's been included in people's environment, deleting the package causes breakage because the URL is gone.

That's why the bot gives you the packages and the command line to do a test-install with the PR built packages before the package actually gets submitted. (If it doesn't appear on its own, run `@biocondabot recheck`).
