### ISSUE TITLE
docker image build-packages.py doesn't run tests

### ISSUE THREAD

**Issue by hardingnj** [bioconda/bioconda-recipes#1507]
The docker test build functionality doesn't run tests.

`docker run -v /home/bioconda-recipes:/bioconda-recipes bioconda/bioconda-builder --packages pybigwig --env-matrix /bioconda-recipes/scripts/env_matrix.yml`

Yields
> Ran 0 tests in 9.964s

Despite tests being defined in the meta.yaml

**Comment by hardingnj** [comment]
(they are run with conda build recipes/pybigwig)

**Comment by roryk** [comment]
Same issue.

**Comment by tomkinsc** [comment]
I'm seeing the same problem.

**Comment by daler** [comment]
In this case, the output of "Ran 0 tests" is nosetests saying that no packages were built. A package won't be built if it already exists in the bioconda channel. If you're expecting a package to build but it doesn't, the most common reason is that the version already exists in the channel and you need to bump the build number in order to trigger a new build for the same version.

Also for local builds with the docker container the `--verbose` flag is pretty handy.

Details: the build script is set up as a nosetests test suite where each build is considered a test. Each build consists of a `conda build` call, which will run the tests defined in `meta.yaml` after a successful build. So here it looks like nothing's being built in the first place.

**Comment by bgruening** [comment]
A lot has changed during May. Please feel free to reopen if this is still an issue.
