### ISSUE TITLE
Installation Ariba

### ISSUE THREAD

**Issue by MichWeb75** [bioconda/bioconda-recipes#15223]
Hi,
I get an error when installing ariba with bioconda.

```
conda install -c bioconda ariba 
CondaValueError: Malformed version string '~': invalid character(s).
```

**Comment by npavlovikj** [comment]
I tried installing "ariba" on both Linux and OSX, and everything worked fine...

Few things to maybe try:
1. Make sure you have the proper channel order, e.g. **conda install -c conda-forge -c bioconda -c defaults ariba**. "ariba" uses dependencies from all these 3 channels.
2. Make sure you have newer version of conda installed, the current one is 4.6.
3. In case you have copied the command, makae sure to type "-" instead of copying it from somewhere.
4. Finally, I would try "conda create" instead of "conda install", e.g. **conda create -n ariba -c conda-forge -c bioconda -c defaults ariba**

I hope any of these suggestions works for you.
