### ISSUE TITLE
bioconductor-biocgenerics incompatible with r-base=3.6.0

### ISSUE THREAD

**Issue by khughitt** [bioconda/bioconda-recipes#15736]
The most recent version of bioconductor-biocgenerics available appears to depend on an older version of R:

```sh
conda search -c bioconda bioconductor-biocgenerics --info | tail -18

bioconductor-biocgenerics 0.28.0 r351_1
---------------------------------------
file name   : bioconductor-biocgenerics-0.28.0-r351_1.tar.bz2
name        : bioconductor-biocgenerics
version     : 0.28.0
build       : r351_1
build number: 1
size        : 695 KB
license     : Artistic-2.0
subdir      : noarch
url         : https://conda.anaconda.org/bioconda/noarch/bioconductor-biocgenerics-0.28.0-r351_1.tar.bz2
md5         : 981aa970146a0d2ec0f740cb1cb8e42b
timestamp   : 2018-12-08 23:28:29 UTC
dependencies: 
  - r-base >=3.5.1,<3.5.2.0a0
```

... With the net effect that (many) conda bioconductor packages (e.g. bioconductor-organismdbi) cannot be used used with R 3.6.0:

```sh
conda create -n bioc-test -c bioconda r-base=3.6.0 bioconductor-organismdbi

Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - bioconductor-organismdbi -> bioconductor-annotationdbi[version='>=1.44.0,<1.45.0'] -> bioconductor-biobase[version='>=2.42.0,<2.43.0'] -> bioconductor-biocgenerics[version='>=0.28.0,<0.29.0'] -> r-base[version='>=3.5.1,<3.5.2.0a0']
  - r-base=3.6.0
Use "conda search <package> --info" to see the dependencies for each package.
```

**Comment by PertuyF** [comment]
R `3.6` is not supported by `conda-forge` and `bioconda` at this time.
It will likely be built only after first patch release (`3.6.1`, if stable enough), then it will require rebuild of all CRAN and Bioconductor (3.9) packages against this new version of the `r-base` package.
See https://github.com/conda-forge/r-base-feedstock/pull/82 for more information.

So your issue is not linked to `bioconductor-biocgenerics`, but to R 3.6 not being available on Bioconda yet.

**Comment by khughitt** [comment]
Ah got it. Thanks for the clarification linked issue! In that case I will close the issue and wait until conda-forge and bioconda move to 3.6.x.
