### ISSUE TITLE
upload-linux skipped

### ISSUE THREAD

**Issue by armintoepfer** [bioconda/bioconda-recipes#17502]
After updating the binaries of two existing versions https://github.com/bioconda/bioconda-recipes/pull/17501, CircleCI did not upload them https://circleci.com/gh/bioconda/bioconda-recipes/74351. Why?

**Comment by epruesse** [comment]
As far as I can tell, it did. Can you explain your issue in more detail?

**Comment by epruesse** [comment]
Ah, now I understand what confused you.

You used the Bot command to upload and merge. It doesn't need the `upload-linux` and `upload-macos` jobs on CircleCI. Instead of rebuilding the packages after the merge, it just grabs the packages built during your final passing commit to the PR and uploads those. That saves CI time for packages that take long to build and test, and also makes it a bit safer as few people check on the build status of the merge commits' CI processing.

**Comment by armintoepfer** [comment]
Thank you for the explanation. The extra bot behavior is new to me.

**Comment by epruesse** [comment]
(TL'DR: those jobs are not needed when you bot upload. The bot does the upload right away. So they get skipped. The CI jobs exist in case the bot is unavailable.)

**Comment by epruesse** [comment]
https://biocondabot.pruesse.net/commands
