### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#1860]
I think we need more tests for some general cases, like:
- [ ] check if this packages exists in conda-forge, r, default - if so fail
- [ ] a test is included
- [ ] a checksum is integrated
- [ ] meta.yaml syntax checks, linting and the filename
- [ ] check the size of an package - max size package?
- [ ] checksum required; no git_url if possible (_added by Ryan, xref #2194_)

Please add any other ideas.

**Comment by johanneskoester** [comment]
This is a very good idea.

**Comment by tomkinsc** [comment]
I'm not sure it's best to hard-fail (i.e. block merging) if a package already exists in coda-forge, r, default, etc., or at least we'd have to be careful about what we compare. Package name collisions are possible, and we may want to offer a package where other channels may not have a newer version available, or we may want to offer an older version of some package (for example, Trinity v1.x, which uses a different algorithm from Trinity v2.x, which is why there are recipes for both in bioconda). Or we may want to offer a version of a package with different compiler flags, or one that uses a different post-link script, etc. The comparison could include something like $PKG_NAME+$PKG_VERSION+$SRC_URL_PREFIX. The failure could also be displayed in the PR build panel, but be non-blocking.

The other points sound great though.

**Comment by epruesse** [comment]
outdated - got a linter now
