### ISSUE TITLE
Parsing issues in bioawk with bison

### ISSUE THREAD

**Issue by janxkoci** [bioconda/bioconda-recipes#19746]
Hello,

I had some issues with parsing using `bioawk` package (from bioconda) and `bison` parser generator (from conda-forge) and a member of the conda-forge team asked me to ping you, in case you can help find a solution. Here are links to the reported issues:

- https://github.com/conda-forge/bison-feedstock/issues/22 is the issue I raised with conda-forge maintainers about `bison` package,
- https://github.com/lh3/bioawk/issues/34 is my original report to author of `bioawk`, describing exact symptomps of the problems.

Thanks for any help.

**Comment by dlaehnemann** [comment]
I have just discovered a problem with another software that depends on a library that uses `bison`. Its build process broke with the newest bison version `3.8`, because they introduced breaking changes there. Maybe these are causing something similar for bioawk. For the other tool, pinning `bison==3.4` to the latest version before `3.8` that is available via `conda-forge` fixed the problem. So maybe this is something worth trying here, as well.

Here's [the issue where I documented this in the affected library `libpll-2`](https://github.com/xflouris/libpll-2/issues/23).
And here's [the change where the software `raxml-ng` depending on that library got its `bison==3.4` pinning](https://github.com/bioconda/bioconda-recipes/pull/31824/files).

**Comment by janxkoci** [comment]
Actually, my issue was solely caused by my locale. I've updated my original reports and mentioned locale even in the title of the original issue, in hopes to make it clearly visible.

As my issue was resolved by changing locale, I'm closing this issue as there is no change needed here. Feel free to opne a new issue if you have other problems.
