### ISSUE TITLE
MPI support on OSX (gmap)

### ISSUE THREAD

**Issue by jrderuiter** [bioconda/bioconda-recipes#2023]
A number of packages (such as gmap) currently are not built for OSX, which I am assuming is due to the lack of MPI support on a default OSX installation.

For example, building gmap on OSX gives the following error:

```
Error: Did not detect hard-coded path in bin/mpi_gsnap from binary_has_prefix_files
```

Is MPI support (for example using OpenMPI) possible using conda? I tried (naively) adding openmpi as a build requirement for gmap but that does not solve the issue.

We could also just ignore MPI builds for OSX (at least for gmap) using:

``` yaml
  binary_has_prefix_files:
    - bin/mpi_gsnap # [not osx]
```

This works fine here, although it would be omitting proper mpi support.

**Comment by jrderuiter** [comment]
Maybe a bit of an unrelated question, but why are many packages currently marked skip for osx? (Examples being libdb, perl-db-file etc.).

**Comment by bgruening** [comment]
@jrderuiter for most of the packages there is no real reason, just historical. 
We started with a OS-X whitelist and by default nothing was build on OSX. Then there was an effort in removing the OSX whitelist. So we included the skip and removed the whitelist, so that every new package will be build on OSX by default. The idea was to incrementally fix all old packages and build them on OSX as well.

**Comment by bgruening** [comment]
I'm fine with disabling OpenMPI for OSX.
