### ISSUE TITLE
Bioconda increasingly unstable as a platform. Action needed.

### ISSUE THREAD

**Issue by ialbert** [bioconda/bioconda-recipes#21128]
I am an end-user of bioconda and have been using it in education for over four years now. 

Over the last year I have noticed that bioconda is growing increasingly unstable to the point where it may be simpler to maintain a series of installation shell scripts to install the 20 or so essential bioinformatics tools that I teach rather than rely on bioconda.

The **fundamental problem** I have is that that it has become impossible to tell whether conda installation written a given day will actually produce a working system a few weeks later. Way too many changes are made all the time, seemingly haphazard fashion, seemingly with the expectation that testing will find the errors.

The instability in bioconda hurts those that need it the most. I can troubleshoot my system, I have no problem compiling tools from source, but newcomers to bioinformatics can't be expected to be doing so.

Basic tools stop working:

https://github.com/bioconda/bioconda-recipes/issues/21084

it gets worse, as it turns out the R program installed with bioconda cannot compile required packages from source anymore! What?

After all, we are talking about tools like`limma` here, one of the most commonly used packages, not some esoteric sketchy code.

Latest BLAST cannot be installed:

https://github.com/bioconda/bioconda-recipes/pull/20874

And so on. The versioning system and the build system are overcomplicated, extremely difficult to understand. In the last two months, I have seen at least three major complete breakdowns of the utility of simple tools. 

Decisions makers should come together and come up with a plan to simplify the platform, so that breaking the basic, fundamental code does not happen.

**Comment by mbargull** [comment]
I appreciate making us aware of such issues. I really do.
However, apart from the issue reporting, I don't find your comment much constructive in its current state. (Note this is my personal opinion and is not representing one from the core team or other members.)

We are aware of things within Bioconda and outside of it that we can and will improve on. Please note the "outside" part especially: The challenges we have to deal with are often not because of our own "overcomplicated" build system but caused by upstream changes or other external factors. But even then, we still try to handle and fix those too. (And, of course, we appreciate contributions in any way to help us with that.)

----
To get to the specific points you mentioned:

1. > Basic tools stop working:
   > 
   > #21084
   
   This happened due to insufficient information provided by the upstream project (`edgeR` not `limma`, really) as commented in https://github.com/bioconda/bioconda-recipes/issues/21084#issuecomment-604462259.
   I'll fix it.

2. > R program installed with bioconda cannot compile required packages from source anymore!
   
   Can you elaborate?

3. > Latest BLAST cannot be installed:
   > 
   > #20874
   
   This is a *build*, not *installation* issue.
   I'm investigating it. (But I don't have/use Apple computers which makes it tedious -- if a macOS expert wants to lend a hand, I'll gladly take it.)

4. > The versioning system \[...\] overcomplicated, extremely difficult to understand.
   
   Can you elaborate? What versioning do you refer to?


5. > \[...\] the build system are overcomplicated, extremely difficult to understand.
   
   Can you elaborate? Meaning, I'd like to know what parts do you think are most confusing etc.
   I agree that there are things that are more complicated than they ideally should be.
   Your feedback on this would be valuable!

6. > In the last two months, I have seen at least three major complete breakdowns of the utility of simple tools.
   
   If there are additional cases apart from the one you already referenced, please let us know, so we have the chance to understand and fix those.
   (Ideally by creating separate issues for them.)

**Comment by ialbert** [comment]
thanks for following up, I appreciate the efforts.

2. om R I attempted to follow the standard installation methods that a user would be directed to via in the documentation for example: `BiocManager::install("DESeq2")`. These were not successful, compilation would error out. 

4. and 5. I am confused of the builds are supposed to mean, how they  relate to one another.  Some numbers are the same `ha1b3eb9_4` across multiple packages within one installation but then most are not, some seem to encode the version of a say Perl in the name of the build, `pl526h9f37e31_0` but then many other perl modules are simply labeled`pl526_1` perhaps that means "pure perl". Then you have say `picard`, its build number is just `0`. Quite puzzling. Overall it is difficult to make sense of what it all means, how they relate. 

 6. I have made note of those extra cases  @dpryan79 assisted me there. Thus those were taken care of, I was just pointing that there were repeated instances of things unexpectedly not working. 

This is really my concern and I wish to bring to everyone's attention. It affects a lot of people when a process that works one day stops working the next. Is there a way to ensure that if one works out a process then it won't get broken by an update. Basically I wish you had something like pinning version numbers that are meaningful. Pinning to version 1.2.3 is informative than pinning to `ha1b3eb9_4` is not really.

**Comment by mbargull** [comment]
> 2. with R I attempted to follow the standard installation methods \[...\]

You have to provide more -- ideally step-by-step, starting from `conda create` to the `R` comands, -- instructions for me on that one. I'm no user of R so can't tell what "standard" means, unfortunately. If you do, I can take a look.

----
> 4. and 5. I am confused of the builds are supposed to mean \[...\]

Those are not part of the versions but just identifiers to discern between different variants of a package of the same version (e.g., due to how Perl/Python/etc. work, you need multiple builds for multiple of those Perl/Python/etc. versions when you work with a binary package manager). The reason why there are even user readable parts in some of them, e.g., `pl526`, is just historic. Ideally, those would just be random strings like `a1b3eb9` generally to not give the user any impression that one does carry more meaning than the other. But it is hard to get the upstream build tool maintainers to change that in foreseeable time.

I don't know where the best user-oriented documentation for this is. This is a more technical one that came up first for me:
https://conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#info-index-json :
> The build string. May not contain "-". Differentiates builds of packages with otherwise identical names and versions, such as:
> - A build with other dependencies, such as Python 3.4 instead of Python 2.7.
> - A bug fix in the build process.
> - Some different optional dependencies, such as MKL versus ATLAS linkage. Nothing in conda actually inspects the build string. Strings such as `np18py34_1` are designed only for human readability and conda never parses them.

All that said, this is one of those "external factors" I mentioned: This is not something Bioconda came up with but is what the build tools of the whole Conda ecosystem do.

----
> 6. \[...\] I was just pointing that there were repeated instances of things unexpectedly not working.

To be able to act on something, we'd have to be made aware of specific cases.

----
> Is there a way to ensure that if one works out a process then it won't get broken by an update.

The different outputs of `conda-env export --no-builds`, `conda-env export`, `conda list --explicit` may give you an indication on what can be done.

**Comment by johanneskoester** [comment]
> Is there a way to ensure that if one works out a process then it won't get broken by an update. Basically I wish you had something like pinning version numbers that are meaningful. Pinning to version 1.2.3 is more informative than pinning to `ha1b3eb9_4`.

What you suggest is exactly how conda and its channels bioconda and conda-forge should be used. A used should never touch those build hashes, they are just for conda to distinguish different builds. All you need to do to get reproducible environments is to pin up to the patch or minor version number. See for example how we do it in the official snakemake workflows: For example see [here](https://github.com/snakemake-workflows/dna-seq-varlociraptor/blob/master/workflow/envs/varlociraptor.yaml).

Another suggestion: use small environments for specific tasks. It is much more unlikely that they get broken. Moreover, you get more control over which software was actually needed for each task. Workflow management systems like snakemake and nextflow help you with that, however it is also suitable for the manual application.

**Comment by ialbert** [comment]
Thanks everyone for the comments.

@johanneskoester I believe the pinning you refer to would not have avoided this particular breakdown as the library versions did not change. More context below.

@mbargull since `conda-env` wasn't installed I did a search for, it it prints this below, 

```
conda-env                      2.5.2          py27_0  conda-forge         
conda-env                      2.5.2          py34_0  conda-forge         
conda-env                      2.5.2          py35_0  conda-forge         
conda-env                      2.6.0               0  conda-forge         
conda-env                      2.6.0               1  conda-forge         
conda-env                      2.6.0               1  pkgs/main           
conda-env                      2.6.0      h36134e3_0  pkgs/main 
```

it demonstrates why I feel that the entire process is hard to trace. Having seen the information above I have no idea which package will be installed or in what way are the various, identical versions labeled as different builds distinct from one another. 

Looking at the code for `conda-env`, as far as I can tell it is python code that works identically on all python versions. Why does it need a separate "build" for each python, how is that "build" different from another build for the same version. 

I do understand that you did not make the decisions on how conda works - I am just adding context on what I find so confusing, and asking whether a better, simpler policy could be implemented

**Comment by mbargull** [comment]
> @mbargull since `conda-env` wasn't installed

As you are well aware, not every single file/executable has to have its own package (e.g., `blastn`, `blastp` being provided by `blast`. `conda-env` is shipped with the `conda` package, i.e., it is installed with every `conda` installation.

> I have no idea which package will be installed

Right, if you want `some-package` installed with version `X` you install `some-package=X`. You should not have to care about why there are different builds of the package.
(For the reasons why there are different builds, I already hinted at in my previous comment with "multiple of those Perl/Python/etc. versions".)

> simpler policy could be implemented

It is often not a question of "policy" but technical reasons that create such complexities in package management. It would make sense to *hide* some of that complexity from the user (but it is debatable who should/would carry out the work on that, meaning IMO upstream, i.e., Anaconda, not Bioconda should allot resources to improve on that front.)

----
Most of your questions indicate a level of unfamiliarity with Conda (e.g., differences between builds and version or the existence of `conda-env`), hence I can only *strongly* suggest to read the documentation of Conda (and Bioconda). This issue is not the right place to explain those topics.

**Comment by johanneskoester** [comment]
To put this to a positive end. You certainly have a valid point about Bioconda not being entirely rock solid. One (paradox) reason is that conda has matured in the recent months, but this meant to overhaul a lot in the packaging process. It is not always easy to anticipate issues that occur in such cases.

Nevertheless we are aiming to improve upon this. In particular, as part of our Chan Zuckerberg funding, we plan regular weekly testing of packages, not only when they change. This will make us much quicker in detecting breakages, which are e.g. often caused by not anticipated ABI incompatibilities (although we are getting better and better with this, keeping an eye on thousands of packages is hard for a community of volunteers).

**Comment by ialbert** [comment]
@mbargull @johanneskoester thank you both for engaging in this conversation
