### ISSUE TITLE
AUGUSTUS missing intron2exex.pl

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#21498]
Hi,
I installed `AUGUSTUS (version 3.3.3)` but not able to find `intron2exex.pl`.

What did I miss?

Thank you in advance,

Michal

**Comment by npavlovikj** [comment]
@mictadlo , I took a look at this issue, and `intron2exex.pl` is indeed not available in Augustus 3.3.3.
Based on https://github.com/Gaius-Augustus/Augustus/commit/47842adb316b4afc6403cce474e1815f479ac2e6, looks like the script was removed prior to the 3.3.3 release.
The recipe for Augustus 3.3.3 does check for `intron2exex.pl`, but since the output from the command is redirected to `/dev/null`, that will always work even if the script doesn't exist (which is the case here).
`intron2exex.pl` is available in Augustus 3.3.2, so you can install that conda version if you want.

I hope this helps.

Thank you,
Natasha

**Comment by mictadlo** [comment]
Hi Natasha,
Thank you for the link. It appears that `intron2exex.pl` was replaced by `scripts/getIntrons.pl`. Is there any reason why `getIntrons.pl` was not included in this conda recipe?

Thank you in advance,

Michal

**Comment by npavlovikj** [comment]
@mictadlo , as you have already noticed, the script `getIntrons.pl` is not part of Augustus 3.3.3. As part of the Augustus recipe, all scripts from the directory `scripts/` are copied to the environment.
