### ISSUE TITLE
bioconductor-rhdf5 2.16 should require R 3.3

### ISSUE THREAD

**Issue by edurand** [bioconda/bioconda-recipes#2235]
rhdf5 2.16 is designed for Bioconductor 3.3, which itself is built for R 3.3. Allowing rhdf5 2.16 to build and install with R 3.2 creates issues with other bioconductor packages, and in fact makes opening most hdf5 files impossible on my system. 

meta.yaml file should reflect this. 

Thanks, 
Eric

**Comment by daler** [comment]
Thanks. Due to various technical reasons related to the build system infrastructure, we're still working on supporting R 3.3. However the [rhdf5 bioconductor page](http://bioconductor.org/packages/release/bioc/html/rhdf5.html) does not list R >3.2 as a dependency the same way, e.g., [S4Vectors](http://bioconductor.org/packages/release/bioc/html/S4Vectors.html) does. If it were listed then we wouldn't have a broken package. You might want to report this upstream to rhdf5 devs; in the meantime @johanneskoester should we remove packages from anaconda in cases like this?

**Comment by bgruening** [comment]
Since yesterday we have R3.3 builds for hdf5: https://anaconda.org/bioconda/bioconductor-rhdf5/files
