### ISSUE TITLE
Anaconda build migration

### ISSUE THREAD

**Issue by jerowe** [bioconda/bioconda-recipes#2261]
[Blog](https://www.continuum.io/blog/developer-blog/anaconda-build-migration-conda-forge)

I don't feel very up on the different build systems. Will this affect bioconda at all?

**Comment by daler** [comment]
Nope, we're using docker containers on travis-ci rather than anaconda build system -- shouldn't affect us at all.

**Comment by bgruening** [comment]
Ryan this blog is talking about that conda-forge will replace the anaconda build system. So cf will be the new standard. I think this affects us, but we are already discussing how to work together with cf and how to unify the builsystem based on Docker!
Maybe I'm misunderstanding something - sorry.
On Sep 1, 2016 3:44 PM, Ryan Dale <notifications@github.com> wrote:Nope, we're using docker containers on travis-ci rather than anaconda build system -- shouldn't affect us at all.

**Comment by daler** [comment]
My understanding of the post was just that the anaconda build system was being shut down and conda-forge was suggested as a replacement and the way forward. Since we don't use the anaconda build system and have our own build system, then it wouldn't affect us. But as you say, hopefully we'll be able to integrate with conda-forge, at least in terms of build systems and infrastructure.

**Comment by jerowe** [comment]
I don't know much about this and just briefly read the articles, but it looked like conda-forge wants to be a unified repository. Does this mean different channels (bioconda, javascript, etc) go away? 

Will they still be building against centos? I feel like I need so much more information and don't even know what questions to start with!

**Comment by bgruening** [comment]
@jerowe seeing you on all channels nowadays I think you don't have any questions anymore, correct? :)
