### ISSUE TITLE
How to handle multiple versions for a package?

### ISSUE THREAD

**Issue by acaprez** [bioconda/bioconda-recipes#232]
I was just wondering what the procedure was for adding recipes for multiple versions of a particular package.  I didn't see any existing examples offhand in the repo nor do the docs mention it.  In my personal repo I just use a two-level `<package name>/<package version> ` directory structure, but I'm not sure how to handle it here.

**Comment by johanneskoester** [comment]
This is an interesting question. So far, I thought it would be sufficient to keep only the newest version. I would be interested to hear the opinion of all devs here.

Can you provide a use case for having to store multiple versions?

**Comment by acaprez** [comment]
The main use case I'm thinking of at the moment is QIIME.  It requires very specific (and sometime quite dated) versions of its [dependencies] (http://qiime.org/install/install.html#installing-qiime-natively-with-a-full-install).  So it would be nice to be able to keep those alongside the current version.  

Another use case might be for a package that takes advantage of the Features functionality.  For example, if you want to have a MKL and non-MKL version of the same package release, it might be useful to do something like `<package name>/<package version>-mkl`.

I do admit it's also somewhat of a personal preference, but for our environment we often have multiple package versions installed alongside each other on our HPC systems.  It's advantageous for me to keep each version's recipe as a distinct subdirectory.  That way if I need to rebuild and reinstall the older version for some reason it's simpler - I don't need to go back in the commit history to find the previous version.

**Comment by johanneskoester** [comment]
Especially the second use case makes sense. The proposed structure would indeed give us some additional flexibility, and won't really hurt. We could convert our existing try with a simple script that parses the meta.yaml files.

**Comment by johanneskoester** [comment]
@organization/bioconda: any objections, opinions?

**Comment by kyleabeauchamp** [comment]
No comment from me, but I will point out two examples: https://github.com/conda/conda-recipes/tree/master/numpy-openblas and https://github.com/conda/conda-recipes/tree/master/numpy-mkl

**Comment by johanneskoester** [comment]
So, here, openblas and mkl has become part of the name as opposed to the version/build string. That means that packages need to specifically depend on e.g. numpy-openblas?

**Comment by kyleabeauchamp** [comment]
Not quite.  In the meta.yaml, the names are both numpy.  It's just the name of the recipe directory that changed.  Also, I don't think that repository is doing full continuous integration / building, so YMMV.

https://github.com/conda/conda-recipes/blob/master/numpy-openblas/meta.yaml#L2

https://github.com/conda/conda-recipes/blob/master/numpy-mkl/meta.yaml#L2

**Comment by johanneskoester** [comment]
I see. That makes sense.

**Comment by daler** [comment]
Another use-case is to ensure the same versions when reproducing others' work. It's not uncommon for papers coming out now to use software versions from a year or more in the past. So it would be good to at least support the option.

As far as structure, the package/version structure seems pretty straightforward.

**Comment by kyleabeauchamp** [comment]
IMHO I see two separate use cases: reproducibility and simultaneous versions.

So for the reproducibility problem, presumably it would be sufficient to just do, e.g.,  `conda install bwa==0.7`, rather than maintaining a separate recipe for bwa 0.7.  As long as the old version is on the anaconda server, you should be good to go.  When the recipe is updated for a new version, the old binaries will still be available on conda.  

For situations where you need to have two separate versions installed on the same machine, I suppose there's no workaround to having separate recipes and packages.

**Comment by johanneskoester** [comment]
A side note: two versions of the same package on the same machine can be handled using separate environments, and launching the environment directly with ``conda run``.

**Comment by daler** [comment]
Good point -- as bioconda matures, the old versions will be available from when they were added as new versions. I guess I was thinking of the case where someone needs `bwa==0.6` but the oldest in bioconda is 0.7.12.  Separate recipes would provide a mechanism for pre-populating cases like this, but maybe it's not worth the long-term maintenance costs.

**Comment by acaprez** [comment]
So going back to my original QIIME example, it requires cd-hit 3.1.1.  The current existing version in the repo is 4.6.4.  Short of doing something very odd like replacing the 4.6.4 recipe files with 3.1.1 in a new commit and then reverting that, I currently see no way to add 3.1.1  It's a similar situation with other packages; with the current scheme, there's no reasonable way I see then to build up the dependency chain QIIME requires.  

One other thought concerning using the previous version's binary packages without maintaining a distinct  recipe for that version.  That essentially assumes that there will never be a need to go back and rebuild that binary package.  IMHO, that seems a bit of a dangerous assumption.  Perhaps someone is using an older version due to a long-term project and there is a bug that requires the source to be patched?  Or the package was originally built without feature X at `configure` time, which is needed later?  There could be any number of reasons why it may be necessary to rebuild an older version's binary package.

Both of those examples are problems I've run into previously, which is why I ended up with the two-level structure in my own repo.  If there is a more elegant approach to solve issues such as those, I would certainly be open to it.

**Comment by johanneskoester** [comment]
I agree. It won't hurt and we are more flexible.

**Comment by johanneskoester** [comment]
Anybody volunteering to migrate the structure? I won't be able to work on this before the weekend.

**Comment by kyleabeauchamp** [comment]
What will the plan be for the packages that only really need the latest
version.  Will we have to copy paste the recipe upon new release versions?
I still think we could handle this in a one off way for only those recipes
that need multiple versions.  Also, doesn't conda build expect a flat
directory structure of recipes?

**Comment by johanneskoester** [comment]
I would say, if we do this, we should do it consistently for all packages. Conda should not have a problem, it does not consider the directory structure. We just need to point it to the respective subfolders.

There is one downside: if we start doing this, our conda channel will quickly reach the storage limit, and we will have to find some funding for the 49$/month fee sooner than expected. But could be a huge selling point in terms of reproducibility.

**Comment by dkoppstein** [comment]
Hi, I just wanted to point out that regardless of the versioning issue, the storage space will be the same since anaconda.org keeps the old builds by default (and I think we should keep the old builds, even if there is the option to remove them). 

As far as the directory structure goes, I'm sort of agnostic about it. I would like to point out that the homebrew package manager recently shifted from implicitly [determining the old versions using git commits](http://effectif.com/mac-os-x/installing-specific-version-of-homebrew-formula) to having explicit [older version formulae](https://github.com/Homebrew/homebrew-versions), as shown [here](http://apple.stackexchange.com/questions/180341/newest-version-of-homebrew-versions-no-longer-supported) -- so that might be an argument for having explicit directories for each version. 

This is somewhat unrelated, but I noticed that it seems impossible to have python 2 and python 3 binaries in the same conda environment. Theoretically, if a package depended on two scripts, one written in python 2 and one in python 3, would it be impossible to install that package in a single conda environment?

**Comment by johanneskoester** [comment]
You are right, David. My point was, if we keep old versions in the directory structure, our build logic will issue rebuilds even if old packages are deleted from the conda channel. But that is ok. If we really want to get rid of an old version, we can always remove the directory from the git.

Regarding your question: indeed, for such cases you need two separate environments. You can easily invoke software from outside an environment with conda run, though. I like this behavior though, because it somehow forces people to think about finally migrating their stuff to Python 3 ;-).

**Comment by dkoppstein** [comment]
Point taken about Python 3 =) I can't remember what package it was exactly, but I ran into this issue with some packages that conflicted over some version of libxml and thus couldn't be installed in the same environment. Theoretically, if there was a package that depended on both of those packages, it would not be installable via conda. I guess this is just a theoretical criticism of conda, but if I were designing a package manager from scratch, it would be possible to have multiple versions of software coexisting in the same environment (like python 2 and python 3 coexisting in your /usr/local/bin) as long as the file paths and hashes of those files didn't conflict. 

But back to the point, I think the directory structure sounds quite reasonable.

**Comment by chapmanb** [comment]
Does this mean we need a separate directory for every version of every package? Could we do this only for packages that need old versions like the QIIME examples? For most cases, using the `conda install package==version` syntax should solve the issue of pulling older packages and keep us reproducible over time. I'm against things being complicated and having a huge directory tree, so would vote for adding in specific sub-levels to only those that need old versions (`cd-hit/latest` `cd-hit/3.1.1`) and leave standard packages not requiring this as is.

**Comment by dkoppstein** [comment]
How about something like having cd-hit/meta.yaml be the default, and keeping older versions in cd-hit/versions/3.1.1? If versions directory doesn't exist, can ignore. Then we can keep the existing directory structure.

**Comment by johanneskoester** [comment]
I like that suggestion. Sounds like the optimal compromise.

**Comment by acaprez** [comment]
That sounds fine to me as well.  The only complication I see is in the case of rebuilding a package for an older version.  You may need to go back in the commit history to find the recipe files for that version if it's been updated in the meantime, in order to create the version-specific sub-directory.  Hopefully those cases would be relatively few though, so it shouldn't be a major issue.

**Comment by johanneskoester** [comment]
Implemented in pull request #436.
