### ISSUE TITLE
Please do not merge PR for the time being

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#2330]
@bioconda/all we are currently working on the build-system and we have some issues, please do not merge your PR until we are done.

Thanks! :)
Bjoern

**Comment by johanneskoester** [comment]
@bioconda/all, the new build system has been finally fixed. You can go on with your PRs. I had to adapt to various unexpected changes in conda-build 2.0. Sorry for the delay. Time to get some sleep now ;-).

**Comment by lpantano** [comment]
thank u!

sent not from my computer

**Comment by brainstorm** [comment]
Thanks @johanneskoester! Unfortunately I've retriggered the build and the timeouts persist, but nothing we can do since it's anaconda.org timing out, I guess?:

https://travis-ci.org/bioconda/bioconda-recipes/jobs/160205653

And now it also fails but a bit randomly, some anaconda timeouts return exit code 0 and others errors, bizarre:

https://travis-ci.org/bioconda/bioconda-recipes/builds/160205649

:/

**Comment by johanneskoester** [comment]
@brainstorm, retriggering the old build won't help, because it will work with the old checkout, still pointing to the conda-build version with the bugs I have fixed last night. However, your updated version of BRASS should be online already, because it has been built automatically after the fixes.

**Comment by brainstorm** [comment]
That's great, thanks Johannes!

How should I proceed then? Phony commit to retrigger a "fresh" build in order to be able to merge the pull request?:

https://github.com/bioconda/bioconda-recipes/pull/2329

**Comment by johanneskoester** [comment]
You should sync your with current master (e.g. by merging master in).

**Comment by brainstorm** [comment]
Gotcha, thanks!!
