### ISSUE TITLE
Perl GD

### ISSUE THREAD

**Issue by PietJones** [bioconda/bioconda-recipes#2332]
Hi,

I have installed the package on my Mac system. 
`conda install -c bioconda perl-gd`
Though when I import the package in my perl script, I get the error:

`Can't locate GD/Simple.pm in @INC (you may need to install the GD::Simple module) (@INC contains: /Users/jq2/miniconda/envs/python3/lib/perl5/site_perl/5.22.0/darwin-2level     /Users/jq2/miniconda/envs/python3/lib/perl5/site_perl/5.22.0  /Users/jq2/miniconda/envs/python3/lib/perl5/5.22.0/darwin-2level /Users/jq2/miniconda/envs/python3/lib/perl5/5.22.0 .) at test.pl line 4.`

I then noticed that the package was installed in darwin-thread-multi-2level, and that the conda installed perl is only looking in darwin-2level, so I created a symlink of the one folder.

Now the problem that I am having is that the packages is looking for a library that is in my conda's lib folder, but for some reason it is looking in the system lib folder. Is there some environmental variable that I can set to make conda's perl look in the conda's lib folder?

P

**Comment by jerowe** [comment]
Can you print out a perl -V, and see what else is in there? I had an issue once where I had some variables hanging around in my $PERL5LIB when I installed bioconda perl-, and it messed it all up.

**Comment by martin-mann** [comment]
Hi, I just pushed a new libgd and perl-gd version, which should be available in the bioconda channel by now.

@PietJones Please check if the error persists. Note, as @jerowe said: you might have to ensure using the `perl-threaded` from the bioconda channel rather than using the `perl` from the conda default channel. But not sure about that.. (not tested by me)

Hope that helps. @PietJones : If it does, please close the issue..

**Comment by epruesse** [comment]
outdated
