### ISSUE TITLE
Cannot install advntr-1.4.0 on linux

### ISSUE THREAD

**Issue by Jong-hun-Park** [bioconda/bioconda-recipes#24549]
Hi,

I tried to install the latest version of advntr (1.4.0), but 'conda install advntr' tries to install the older version by default. As far as I know, conda tries to install the latest version by default, and I see the version 1.4.0 with the command 'conda search advntr'.
![image](https://user-images.githubusercontent.com/16819490/94285871-247a3a00-ff09-11ea-85dd-6b6b4cf44f14.png)

The previous issue was solved by using 'conda install advntr=1.4.0' on MacOS but didn't work on linux. The following is the error message.
![image](https://user-images.githubusercontent.com/16819490/94286692-33adb780-ff0a-11ea-9972-21833cbbf9c7.png)
Could you please let me know how to fix it?

**Comment by Jong-hun-Park** [comment]
@iquasere Could you please review this issue?

**Comment by iquasere** [comment]
When this was uploaded to Bioconda, it had a hiccup but seemed to successfully be added to the repo. It also is available as 1.4.0 in the [packages list](https://conda.anaconda.org/bioconda/), as a linux package. It might be due to a classic [Anaconda bug](https://github.com/conda/conda/issues/9268). I am over my head here, @dpryan79 have you encountered something like this before?

**Comment by Jong-hun-Park** [comment]
Solved by changing the channel priority mentioned in [this issue](https://github.com/bioconda/bioconda-utils/issues/330). The following command fixed the issue:
conda install -c conda-forge -c bioconda advntr=1.4.0

**Comment by iquasere** [comment]
I'm glad you figured it out! All required repositories should always be specified, and conda-forge before bioconda before anaconda. I confess I never went back to this issue because I know very little myself. Keep rocking! \m/
