### ISSUE TITLE
Submit snakemake pipeline

### ISSUE THREAD

**Issue by iquasere** [bioconda/bioconda-recipes#24564]
Snakemake pipelines are usually run as ```snakemake Snakefile```. My question would be, is there a way to format such a pipeline so it can be submitted to and available through bioconda? If so, how?

**Comment by pb-cdunn** [comment]
We install our pipelines under `etc/`. But I'm curious about what Bioconda recommends.

**Comment by bgruening** [comment]
Imho pipelines should not be in Bioconda but you can store them in a GitHub repo like https://github.com/maxplanck-ie/snakepipes/releases

ping @dpryan79 and @johanneskoester

**Comment by dpryan79** [comment]
There are a few pipelines already in bioconda, though IMO most are poorly structured. In general, for a bioconda recipe you would need a wrapper script that's directly callable, not something like `snakemake some_snakefile`.

Snakemake and other modern frameworks allow rule-dependent environments, so pipelines should really use that rather than the common and bad practice of dumping everything into a single environment (want to update a tool in just a single step? Hope there are no side-effects of that...). That, however, doesn't mesh terribly well with bioconda (as an example, the biocontainer produced will be incomplete), which is why I presume most pipelines don't do this.

So IMO if there's a wrapper script with some reasonable user-exposed options and the biocontainer produced is at least moderately usable it's OK to make a bioconda recipe for it.

**Comment by iquasere** [comment]
I'm sorry for not closing this issue, at the time I did build a wrapper script for [MOSCA](https://github.com/iquasere/MOSCA/blob/master/workflow/mosca.py), from where the Snakefile is called. The way I did it in Bioconda was putting all scripts (including the Snakefile and the wrapper) and some info files in the environment's "share" folder, and symlinking the wrapper to envs' bin. 
I haven't started using biocontainers yet, and maybe in the future will have some headaches about it ahah. For now, the only problem of having such a pipeline in Bioconda is the huge number of dependencies, but fortunately Bioconda handles them well if specifying the versions carefully.

**Comment by pb-cdunn** [comment]
You can use `python -m snakemake some_snakefile`, but you still have to find the snakefile from somewhere.

For a wrapper that has been working reliably, see `ipa` in **pbipa**. We even dump the exact `snakemake` command that we call, so the user can repeat/debug it directly.

There is a recently added bug in **snakemake**, which has caused tons of trouble for **pbipa** in the last 2 months. A fix for that is underway, and a partial fix has been released as **snakemake-5.31.1**. But **pbipa** actually uses **snakemake-minimal**, which is older and stable, another option. When people mix **snakemake** with **snakemake-minimal** in their Bioconda env, they hit this new bug, which I hope will be completely fixed soon. (Search snakemake in github if you're really interested. I won't link it here.)

> [P]ipelines should really use [rule-dependent environments] rather than the common and bad practice of dumping everything into a single environment (want to update a tool in just a single step? Hope there are no side-effects of that...). That, however, doesn't mesh terribly well with bioconda (as an example, the biocontainer produced will be incomplete), which is why I presume most pipelines don't do this.

Exactly! Getting everything installed on a user's host is the hard part. Bioconda solves that problem reasonably well, so we make other compromises to work with it. But dpryan79 is right, ideally.
