### ISSUE TITLE
remove old version from the repository

### ISSUE THREAD

**Issue by samuelecancellieri** [bioconda/bioconda-recipes#25585]
Hi everyone,
as in the title, is it possible to remove any version from the repository to avoid confusion in the user?

Thanks a lot.

**Comment by tomkinsc** [comment]
By default, conda will always install the latest version of a package as long as its dependencies are compatible with what the user has installed and/or what conda can update them to while maintaining compatibility with other packages installed in the environment. "Latest" is defined by how it interprets version strings, which is described [here](https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html). If an old version is being installed rather than a more recent version available on bioconda, it usually means the newer version has a dependency that is incompatible with someone else installed in the environment that cannot be updated, usually for the same reason. It can help to have separate environments for packages requiring fundamentally incompatible dependencies.

It is possible to remove old build if there is a good reason to do so, but we try to keep old versions of packages in the [channel repository](https://anaconda.org/bioconda/repo) to support reproducibility of methods, so older processes can be run again using the original versions of packages and their dependencies.
