### ISSUE TITLE
Build optimization

### ISSUE THREAD

**Issue by bgruening** [bioconda/bioconda-recipes#2781]
Currently, if someone merges a PR into master and a second PR is created afterwards, this second PR will also build the content of the first merged PR. One solution would be to only build packages that have a modified meta.yaml file in the TRAVIS_COMMIT_RANGE.

**Comment by daler** [comment]
The `--quick` option in bioconda-utils does something close to this. It will only build recipes different from master, e.g.:

* https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/build.py#L215
* https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/utils.py#L431

Simple enough to add this -- just need to change `.travis.yml` from

```yaml
   - BIOCONDA_UTILS_ARGS="--loglevel=info --mulled-test"
```
 to 
```yaml
   - BIOCONDA_UTILS_ARGS="--loglevel=info --mulled-test --quick"
```

**Comment by bgruening** [comment]
Why not activating it by default?

**Comment by daler** [comment]
I figured it was more robust to do the full check against what's been uploaded to anaconda. This is mostly to handle corner cases, like if a merge to master is still building dependencies needed by a PR, but the PR wouldn't build it because it's not different from master. I guess the latter could be solved by paying attention to what was just merged into master and making sure those recipes are independent of the PR.

**Comment by bgruening** [comment]
I'm fine with this! Feel free to merge :) https://github.com/bioconda/bioconda-recipes/pull/2785
