### ISSUE TITLE
recipe updates : how is upstream runtime stability ensured?

### ISSUE THREAD

**Issue by martin-mann** [bioconda/bioconda-recipes#2911]
Maybe a very stupid question, but just tell me if so, no prob. :)

Given the situation that I or somebody updates a recipe pushing a new version. Is it and how is it ensured that all packages depending ON the changed package are still working when freshly installed (with the updated package)? (might be related to #2904 )

Would it be possible to setup a (travis?) check that 
- identifies all directly upstream packages (of bioconda) and
- runs ONLY the tests of that package again (excluding the build)

This is not sufficient for build dependencies (like libraries) but much cheaper than a full rebuild of all upstream packages (which is not feasible to my imagination). 
BUT it might already trigger enough runtime-fails to identify packages where the recipe has to be updated with according `<NEWVERSION` tags for the updated dependency.

**Comment by daler** [comment]
@johanneskoester had set up https://github.com/bioconda/bioconda-tests to do this. The infrastructure is there, we just have to work out details.  I forget what the issues were . . . I think one of them was long build times on travis consuming resources that could otherwise go to building new recipes. Maybe we could restrict the DAG as you mention to speed things up. The new tools in bioconda-utils should help with this.

**Comment by johanneskoester** [comment]
Indeed, I hope to reactivate this at some point. The problem was that the load became too high. However we could either use a different ci, or run the tests in an alternating way, e.g. only test a sample of the recipes per week.

**Comment by martin-mann** [comment]
Hi both, thanks for the feedback so far.

Did you run "only" the tests without build (ie the tests registered within the meta.yaml and not the `make test`)? I am quite surprised that this takes so long.. but this is something easy to "parallelize" via chunking up the list of dependencies to test into blocks.. but anyway.

Maybe to illustrate the problem I see here a small example about two (perl) tools A and B with dynamic runtime dependencies, ie B depends on the API of A. So package B was written in a way (as most packages), such that it comes with a minimal version vor A but no max, since we want to have all bug-fix updates etc. So if I install B I get the recent A loaded too. (right?)

Now A is updated to a new version that changes the API (dropping the parts needed for B), which goes unnoted in the current setup since the build of A goes fine.

If B is now installed, the updated A is pulled and B crashes dramatically without any visible reason.

This whole scenario could be avoided if on build of package A for a new version V
- all direct upstream dependent packages are identified (B)
- the test of each package (B) is run
- if the test fails, the meta.yaml (of B) is automatically updated (with `- A <V`)

What do you think?

**Comment by johanneskoester** [comment]
Yes, only the tests. Indeed, we parallelized them across the connected dependency subdags. With over 1500 packages, it is just a lot of downloads. Also, travis penalizes based on the number of spawned jobs and so on. There is certainly room for tuning the tradeoffs.

The scenario you describe was exactly the reason why I wanted the continuous (weekly) testing of all packages.
Your solution is interesting, because it would at least catch all problems that are introduced by our own updates. It would not capture problems introduced by updates in the default, R or conda-forge channel though.

I would hesitate to automatically update recipes based on this (there can be different reasons for later failures that API changes). However, it is certainly an option to add automatic testing of downstream dependencies to bioconda-utils. This would enforce the fixing of all downstream recipes when updating a certain lib in a PR. What do you think, @daler?

We still would need the old weekly testing solution to capture all other problems.

**Comment by bgruening** [comment]
Just to recap: We are talking here about the problem that, let's say, matplotlib is released in version 2.0, it will potentially break all package that depends on `- matplotlib` and what we are searching here is a solution to automatically detect these things and update packages to `- matplotlib <2.0,>=1.0`. Some holds true for boost, zlib, R ...

If so, we did discuss this before and I was told this is an non-issue and for all libraries we should use the [environment modules](https://github.com/bioconda/bioconda-recipes/blob/master/scripts/env_matrix.yml) or the `x.x` syntax to build against a variety of libraries at once.

The environment idea 
-----------------------------

The environment idea is pinning __one__ specific version for the entire repository. If we want to update boost for example we need to rebuild all packages which have a boost dependency.

* With our ever growing package list I think this solution will not be practically soon (with our travis based build system). Until know we needed 30 PR to rebuild all R packages, this is a huge effort and takes a lot of time :(

* We are pinning now against boost 1.60, but upstream and in conda-forge there is a newer version resulting in incompatible environments.

The `x.x` idea
-------------------

The `x.x` idea was a little bit smarter and was able to build against multiple versions of a library, like numpy and until know was only considered for real libraries with an ABI.

* this could solve a lot of our problems, but it will increase dramatically the amount of packages we need to build and store, which I think is out of question with our current setup :(


Weekly testing
-------------------

I love testing, the more the better! Realistically I see three problems:
 - Build time. Assuming we will have 3000 packages in a year how should this be tested? Even with a random set every now and then, this get unfeasible. It simply does not scale.
 - What is with `old` packages that are hidden in git? We do not test them?
 - If we find problems, there needs to be a team that fixes them.

--------------------

I don't see that we (the small core-team) have (yet) the ability to solve this problem on our own. We need more hardware, a build-farm, a larger core team ... essentially paid infrastructure for bioinformatics ...

@johanneskoester you might remember that I had the same question one year ago but I quickly realized that this is practically not possible atm. So my solution was and still is capturing environments downstream.


Capturing environments
--------------------------------

1. Docker
We have now a saved conda based installation of all our packages in a Docker container. I see this as a freezed version, that is guaranteed to work as it was freezed at build time.

2. `requirements.txt` files
A more lightweight solution is to capture environments in `requirements.txt`. I would like to document this feature more to our users and to help us to solve problems later on.
What I can imagine is something like we create (and with this `document`) to every package we have, during merge-time, in a `requirements.txt` file. This file will help us fixing packages if they break and make everything more transparent.

3. snakemake and Galaxy
We should really advertise environments like snakemake and Galaxy which can work with multiple environments at the same time and for example make it possible to run one R library against 3.2 and in a next step against R 3.3.

4. We need to store/keep old recipes, otherwise it really get's complicated to fix things for our community.


Does this make sense? Or did I miss the topic?


Ping @jmchilton as this might be interesting for you as well.

**Comment by martin-mann** [comment]
Another point I see in that direction (was about to put another issue) is

# Would it be possible to provide the list of dependency versions used for the package build?

This would enable an easier bug tracking once a package is (automatically or manually) reported to fail. In that case, one can compare the build version list with the one that failed.

**Comment by johanneskoester** [comment]
@martin-mann yes, but that would be an extension to conda. Feel free to issue a request or check if it is already possible or planned. I would like to see something like that.

**Comment by martin-mann** [comment]
the dependency list conda request was moved to conda-build : [https://github.com/conda/conda-build/issues/1534](https://github.com/conda/conda-build/issues/1534)
