### ISSUE TITLE
docs overhaul

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#2915]
Currently we have documentation spread across:

- `docs/index.rst` (hosted on bioconda.github.io/bioconda-recipes, along with package documentation)
- README.md
- GUIDELINES.md
- FAQs.md
- CONTRIBUTING.md

The first one is mostly just for users while the rest are for developers. It gets confusing, and we're lacking a single cohesive place to point folks for information.

To start addressing this I've started a docs overhaul which is currently hosted on https://daler.github.io/bioconda-docs. It recycles old content (mostly GUIDELINES and FAQs), but a major addition is a troubleshooting section with an annotated travis-ci log to help orient new contributors.

Note that the simplified setup docs reflect the recent changes in #2914.

Automatically-generated pages for each package are missing from these new docs. We have enough packages now that the sphinx-built package pages and search is very clunky and not very useful IMHO for finding packages. Instead I think it would be nice to have something in client side javascript (DataTable?) that can be searched/filtered, and maybe even a d3.js DAG showing dependencies and reverse-dependencies of packages selected in the table.

So there are several things I'd like to get feedback on:

1. The docs are currently under a separate repo `bioconda-docs` under my account. Moving them to the bioconda organization is trivial, but where should they eventually live? A separate `bioconda-docs` repo? Part of `bioconda-recipes`?

2. How can be best make recipes discoverable and searchable? (ping @ewels )
 
3. We need to document bioconda-utils as well. It's so tightly coupled to bioconda-recipes that one option would be to document it within these bioconda-recipes docs. I have a "build system" placeholder section for this. But it could also be argued that bioconda-utils docs should stay in the bioconda-utils repo. Any preferences on this?

**Comment by bgruening** [comment]
My vote is for including all docs in bioconda-utils, this makes PR and enhancements fast and does not infer with the build setup. I think a third repo is not needed. Before we do this, I think it would be good to restructure our recipe directory and implement the subdir idea for r, bioc and perl packages. This will also make recipes more discoverable.

**Comment by daler** [comment]
Quick turnaround is a good reason for having source in bioconda-utils. And we can host on bioconda.github.io (rather than say bioconda.github.io/bioconda-utils). But I'm not sure I see a reason to hold up docs while we reorganize.

**Comment by daler** [comment]
@johanneskoester would you be OK with moving https://daler.github.io/bioconda-docs to the main bioconda docs hosted on bioconda.github.io?

**Comment by kyleabeauchamp** [comment]
"The conda supports Windows, but most bioinformatics software does not. Therefore bioconda supports only 64-bit Linux and Mac OSX."

"Bioconda supports only 64-bit Linux and Mac OSX."

**Comment by kyleabeauchamp** [comment]
*edit maybe just cut the first line entirely.

**Comment by daler** [comment]
Thanks, changed.

**Comment by ewels** [comment]
Love it - looks great! Big improvement over the existing docs.

My suggestion for making recipe discovery would be two items:

1. A search box on the left which searches just package names.
    * Uses a Javascript [typeahead](https://twitter.github.io/typeahead.js/) widget (or similar) to suggest matching packages.
    * Clicking a result takes you to the page for that package.
2. A dedicated page listing all packages in a table.
    * Columns for name and also also keywords (eg. `aligner`, `RNA`) and dependencies, URL, version etc. (**NB**: would require some extra metadata collection?)
    * Client side filtering for any of these columns using [Datatables](https://datatables.net/) as you suggest, or something similar.

Maybe after this is done we could look into some kind of DAG. But honestly I can't really see _many_ people using that.. A table of dependencies on each package page would probably suffice?

You could add checkboxes to the package table too, then automatically write an installation command for selected packages. Pretty trivial for users to do themselves, but also easy to implement once you have all of this in a table.

Note that I think it would be nice to keep the current URLs for packages if possible, as I bet there are lots of external links kicking around pointing to them. Would be nice if we could do some kind of URL rewriting so that we don't have to have `README.md` on the end of URLs though.

Phil

**Comment by johanneskoester** [comment]
This is great, thanks @daler! @ewels proposal sounds reasonable. I would be fine with replacing the current docs, but let us indeed make sure that old URLs don't break, as @ewels suggests. We can move over the new docs to bioconda and set everything up under `bioconda.github.io/bioconda-utils`. Once we are confident that everything works, we can move it to the `bioconda.github.io` and replace the old docs.

**Comment by daler** [comment]
Thanks all. The docs source are now living in https://github.com/bioconda/bioconda-utils/tree/master/docs and the rendered docs are at https://bioconda.github.io/bioconda-utils.

Next will be building the package pages (pulling from bioconda-recipes' master branch), and then after that will be the javascript stuff.

**Comment by daler** [comment]
A client-side filterable table using DataTables is now at http://bioconda.github.io/bioconda-utils/recipes.html. Individual package pages are also built and have the same url, modulo the `bioconda-utils` subdir.

**Comment by ewels** [comment]
Great! Awesome work :) A few speed thoughts:

* Would be nice if the package name in the table was linked to the docs page
* Probably don't need all three links in the table?
  * I think it's probably fine to link through to the docs page first for this info
  * If keeping them, would be nice to switch them to icons instead of text
  * Doing this means one row of text, thinner rows
* Linux / OSX would be nice as icons too
  * Maybe separate columns, to make it easier to search / filter?
  * Checkboxes to filter for system above table perhaps?
* Is it worth having a separate row per version?
  * It means some duplication, but makes it clearer that different versions are available as individual packages
* Would be nice to have an option to display all rows
* Could throw in version information as we have it already?
* The serif font is nice for paragraph text, but I find it difficult to read quickly in this table

Sorry if that sounds negative, it's not intended to - this is a great new feature! Shout if you would like me to do anything.

**Comment by ewels** [comment]
Also - what are your thoughts on collecting some extra metadata for packages such as keywords? I think generally that the site tends to assume that you already know what package you need - would be nice for beginners / general package discovery if we could squeeze in more explanation information somehow. I can imagine filtering for keywords "RNA" and "QC" for example to see what is available.

Could also have a search box per column (see [docs](https://datatables.net/examples/api/multi_filter.html) - but I usually [move these boxes](http://stackoverflow.com/questions/17629060/how-to-place-datatables-column-filter-on-top) into the header instead).

**Comment by johanneskoester** [comment]
@daler this is truly amazing! Much better than what we had before. I agree with making the rows thinner, probably linking to the details page only. Indeed the serif font looks a bit crowded in the table. Maybe we should switch to sans-serif for everything?

**Comment by daler** [comment]
@ewels awesome comments, thanks so much. The only think that will be tricky I think is the keywords. Grepping recipe descriptions would be a first pass, but I bet there would be a lot of false negatives which would hurt discoverability. I feel like it would be easier to manually maintain a separate keywords tsv or yaml rather than retroactively add keywords to each recipe.

Not sure what you mean by throwing in version information. Do you mean e.g. python version? 

Anyway, I'll give your suggestions a shot. I'll work on the table contents first and leave the JS for last in case you have a chance to tweak that stuff (show all rows; filter checkboxes).

**Comment by daler** [comment]
@ewels do you have any icon source suggestions for osx/linux?

**Comment by ewels** [comment]
Yup! I usually use [Font Awesome](http://fontawesome.io/) as a first stop for web icons.

I agree that keywords probably need to be manually curated. Maybe as part of the build scripts? I guess that this would have to grow fairly slowly over time..

For versions, I meant that instead of this:

Name | Version | Links | System
--|--|--|--
abyss | 2.0.1, 1.9.0 | install| recipe| homepage | Linux & OSX

we could have this:

Name | Version | Links | System
--|--|--|--
abyss | 1.9.0 | install| recipe| homepage | Linux & OSX
abyss | 2.0.1 | install| recipe| homepage | Linux & OSX

Just to make it clearer that there are separate packages available for the same software..

oh, wait I think you're referring to this?
> Could throw in version information as we have it already?

Hah, I think this was a typo on my part sorry. I meant _licence information_. My bad.

Phil

**Comment by daler** [comment]
@ewels @johanneskoester I made most of the changes except for the column-specific search.  License makes the rows a little wide, might take some css tweaking or a different sphinx theme to fix. 

I think another change will be to parse the repodata.json to get all available recipes, not just those that are maintained as independent recipes. 

Note I'm currently building-and-pushing locally using the `build-docs.sh`. Still need to add a github token for building-and-pushing from travis.

**Comment by ewels** [comment]
Fab, great work @daler - looks brilliant! Could we do some kind of clever standardisation + shortening of licence names for the table perhaps? Just abbreviations would probably be fine as long as the full info is available when following a link to the full page. Though to be honest I think it looks good as it is now, so probably not necessary.

**Comment by kyleabeauchamp** [comment]
Presumably license standardization is something that we ought to eventually do in the actual recipes, rather than via the docs.  E.g. we might even want our linter to flag unusual license abbreviations.

**Comment by johanneskoester** [comment]
I agree @kyleabeauchamp. The table is actually good to find recipes to fix in this regard.

**Comment by daler** [comment]
#1581 started to address this. Now that the build system seems to have settled down and the docs are under control, a linter is probably next on the list.

**Comment by daler** [comment]
Docs are now being built on travis and are being pushed to https://bioconda.github.io/bioconda-utils. To get it onto the more-official https://bioconda.github.io, it will just be a matter of changing the [BRANCH and ORIGIN vars](https://github.com/bioconda/bioconda-utils/blob/master/build-docs.sh#L15) in the build script.

**Comment by ewels** [comment]
Great stuff! How's it going with the quick-search box? Shout if you want me to do anything. The twitter typeahead thing I linked to above is probably a bit old and bulky now - something like [this](https://goodies.pixabay.com/jquery/auto-complete/demo.html) or [this](https://www.devbridge.com/sourcery/components/jquery-autocomplete/) is probably more lightweight and suitable.

Phil

**Comment by ewels** [comment]
..could also be nice to have a JSON package URL generally for other people to access and use as a sort of API?

**Comment by daler** [comment]
@ewels https://bioconda.github.io/bioconda-utils/recipes.html#recipes has a search box at the top, do you mean somewhere on the main page? Please have a go if you have time on the quick-search or json stuff. 

@johanneskoester Old bioconda-recipes README/FAQs are getting out-of-date, causing some confusion. OK to move these soon to the main docs and edit bioconda-recipes/README to point there?

**Comment by ewels** [comment]
Yeah, I was thinking of the "Quick Search" box on the left. That's where I would first think of looking for a package and would be a nice way to get to specific module pages quickly from the homepage. Currently I get no results using it for any packages either, which is a separate issue.

**Comment by johanneskoester** [comment]
@daler, your new docs are in a good condition, so feel free to merge move them over to the main url.
Remaining issues in my opinion:

1. The logo URL on the top left seems to be broken, nothing is displayed.
2. I would like to have sans-serif fonts, because it looks less crowded to me. But that is a personal opinion maybe.
3. Can the list of packages be added directly to the menu on the left? Should be easier to find it like that.

**Comment by daler** [comment]
@ewels @johanneskoester docs are now merged into bioconda-utils master and pushing to bioconda.github.io. Went with plain boring Arial for now out of laziness, can play later with that. Logo is fixed too.

Quick-search will still take some more work -- need to refactor `generate_docs.py` to also output JSON rather than just generating the various READMEs so a new search box can use it. As a temporary measure I tried to make the "Available recipes" links more prominent, and removed the broken built-in sphinx search box. I think in this case it was broken due to an interaction between the sphinx theme, the quicksearch, and the fact that the `toctree` needs to be hidden for all recipes to avoid swamping all the TOCs.

Anyway, with the exception of the quicksearch, this seems to be in a reasonably stable state so closing this issue.

**Comment by ewels** [comment]
This is really nice, great work @daler! Sorry I haven't contributed yet, been a hectic few weeks. I'll see if I can get the site up and running locally over the next couple of weeks and do my own PR (away for a couple of months after Christmas, so will be quiet then).

**Comment by daler** [comment]
Thanks @ewels. If you do end up having time it's straightforward to build locally in the `bioconda-utils` repo by running `make html` from the [`docs` directory](https://github.com/bioconda/bioconda-recipes/tree/master/docs), assuming you're already set up for [bioconda-recipes development](https://bioconda.github.io/contribute-a-recipe.html#update-repo-and-requirements).

To avoid building the 1500+ READMEs, the easiest thing is to edit [this line](https://github.com/bioconda/bioconda-recipes/blob/master/docs/generate_docs.py#L82) from 

```python
for folder in os.listdir(RECIPE_DIR):
```

to 

```python
for folder in os.listdir(RECIPE_DIR)[:10]:
```

Output goes to `docs/build/html`.
