### ISSUE TITLE
samtools on macosx is incompatible with freebayes

### ISSUE THREAD

**Issue by MartinL1106** [bioconda/bioconda-recipes#30296]
Hello, 
I'm working on MacOS Big Sur 11.5.2, I found that when I installed "freebayes" from bionconda, my samtools downgraded from 1.13 to 1.4.1, and then when I can'u use samtools, with the message:
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/Use name/opt/miniconda3/bin/samtools
  Reason: image not found
Abort trap: 6

when I re-install samtools, the freebayes was removed..

But I have a python code needs both samtools and freebayes, do you have some idea for fixing this problem? 

Thanks for your help

**Comment by jmarshall** [comment]
Bioconda currently has HTSlib 1.12 pinned, and the current freebayes package has therefore been built against that version.

Samtools 1.13 requires htslib 1.13, and has an exception to the pinning (via its own _conda_build_config.yaml_ file) that means it requires the htslib-1.13 package.

Hence freebayes and samtools-1.13 are incompatible. You could install them into separate conda environments and add both bin directories to $PATH for your python code, or you could use samtools-1.12 with

```
conda create -n myenv freebayes samtools=1.12
```

(Unfortunately the plain installation command with `samtools` rather than `samtools=1.12` has selected the ancient now mostly broken version instead of the 1.12 that it could have selected, so you need to specify it explicitly.)

Note that samtools-1.12 has a serious known bug: samtools/htslib#1279. But otherwise it's a lot better than 1.4.1 and you don't have to juggle openssl/libcrypto dependencies.

This is a pretty good demonstration that Bioconda's current policy of “pin HTSlib, but allow an exception for widely used packages like samtools & bcftools” is not really tenable…

**Comment by MartinL1106** [comment]
> Bioconda currently has HTSlib 1.12 pinned, and the current freebayes package has therefore been built against that version.
> 
> Samtools 1.13 requires htslib 1.13, and has an exception to the pinning (via its own _conda_build_config.yaml_ file) that means it requires the htslib-1.13 package.
> 
> Hence freebayes and samtools-1.13 are incompatible. You could install them into separate conda environments and add both bin directories to $PATH for your python code, or you could use samtools-1.12 with
> 
> ```
> conda create -n myenv freebayes samtools=1.12
> ```
> 
> (Unfortunately the plain installation command with `samtools` rather than `samtools=1.12` has selected the ancient now mostly broken version instead of the 1.12 that it could have selected, so you need to specify it explicitly.)
> 
> Note that samtools-1.12 has a serious known bug: [samtools/htslib#1279](https://github.com/samtools/htslib/issues/1279). But otherwise it's a lot better than 1.4.1 and you don't have to juggle openssl/libcrypto dependencies.
> 
> This is a pretty good demonstration that Bioconda's current policy of “pin HTSlib, but allow an exception for widely used packages like samtools & bcftools” is not really tenable…

Thanks for your answer, I will try it !

**Comment by dpryan79** [comment]
I've just tagged a new bioconda-utils that updates the htslib pinning to 1.14. I'll start rebuilding everything over the weekend, which should resolve this issue.

**Comment by suhrig** [comment]
> I'll start rebuilding everything over the weekend

@dpryan79: Does this mean that all packages currently depending on htslib 1.12 will be rebuilt with 1.14 as a dependency? How long will the rebuilding take? Or am I misinterpreting your statement, and packages depending on htslib 1.12 need to be rebuilt manually? If so, how?
