### ISSUE TITLE
samtools s3 protocol not supported

### ISSUE THREAD

**Issue by kzuberi** [bioconda/bioconda-recipes#3042]
I believe support was added in #1650, however it seems to not work in the current bioconda samtools build for both OSX and Linux (protocol not supported error):

```
(biotools) $ conda list samtools
# packages in environment at /home/ubuntu/miniconda2/envs/biotools:
#
samtools                  1.3.1                         4    bioconda
(biotools) $ samtools view s3://1000genomes/phase1/data/NA12878/exome_alignment/NA12878.mapped.illumina.mosaik.CEU.exome.20110411.bam 20:1000-100000
[E::hts_open_format] fail to open file 's3://1000genomes/phase1/data/NA12878/exome_alignment/NA12878.mapped.illumina.mosaik.CEU.exome.20110411.bam'
samtools view: failed to open "s3://1000genomes/phase1/data/NA12878/exome_alignment/NA12878.mapped.illumina.mosaik.CEU.exome.20110411.bam" for reading: Protocol not supported
(biotools) $ 
```

https fails with a similar error. Interestingly the s3 protocol does work with bioconda pysam.

Quick workaround was to drop-in the samtools build from the biobuilds channel (where the above view command worked with protocol s3 without trouble). I assume then there is still some packaging problem for the bioconda version?

**Comment by daler** [comment]
@bioconda/core any ideas on this?

**Comment by chapmanb** [comment]
Khalid -- thanks for the report and sorry about the issues. It looks like this was a problem with how we were linking against libcurl -- the top level configuration now over-writes the htslib one so I had to pass a flag to enable at two levels. I pushed a new version of samtools (1.3.1-5) that now works correctly with S3 URLs.

As a side node, this also updates samtools to use the new build system and I had to disable tview due to an incompatibility with ncurses from the default channel, which we now get rather than the one from the r channel. If anyone understands this better than me and wants to tackle it I left a note about a reported issue on the samtools issue tracker in the build.sh and on the current PR.
