### ISSUE TITLE
Documentation to contribute recipes is outdated

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#32994]
Hi,
I would like to contribute recipes but the current documentation does not include how to deal with GitHub's tokens

```
$ git clone https://github.com/mictadlo/bioconda-recipes.git
Cloning into 'bioconda-recipes'...
remote: Enumerating objects: 312339, done.
remote: Total 312339 (delta 0), reused 0 (delta 0), pack-reused 312339
Receiving objects: 100% (312339/312339), 332.37 MiB | 9.93 MiB/s, done.
Resolving deltas: 100% (172897/172897), done.
Updating files: 100% (18842/18842), done.

$ cd bioconda-recipes/
$ git remote add upstream https://ghp_eWgtJStONjyA40srOLuSCnEQ0rrdza@github.com/bioconda/bioconda-recipes.git
$ git checkout master
Already on 'master'

$ git push origin master
Username for 'https://github.com': mictadlo
Password for 'https://mictadlo@github.com': 
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/mictadlo/bioconda-recipes.git/'
```

Thank you in advance,

Michal

**Comment by marcelm** [comment]
This is not a Bioconda issue in particular. You’re getting this message because the way you are trying to acces your repository mictadlo/bioconda-recipes (which happens to be a fork of the bioconda-recipes repository) is deprecated. You need to read the Blog page that the message links to and follow the instructions, that is, either use SSH to access your repo or use an access token. This would have happened for any other of your own repositories. (You’d get the error message even if you left out the `git remote add upstream` part).
