### ISSUE TITLE
macOS version of mothur is behind the linux version

### ISSUE THREAD

**Issue by kelly-sovacool** [bioconda/bioconda-recipes#34102]
mothur v1.47.0 is available on Linux via bioconda, but only v1.44.11 is available on macOS. Is there something wrong with the recipe that makes it incompatible with macOS?

https://anaconda.org/bioconda/mothur
![image](https://user-images.githubusercontent.com/17768269/161598376-5573fcf1-c6ee-49fa-8de5-b5230c6be9f6.png)

**Comment by kelly-sovacool** [comment]
@bioconda/core any insight into this issue?

**Comment by kelly-sovacool** [comment]
Could this be related to the fact that there never was a `v1.44.11` and it was just a mistag?
https://github.com/bioconda/bioconda-recipes/pull/21880

**Comment by AlexTate** [comment]
Builds for macOS haven't been performed due to [the preprocessing selector on line 14](https://github.com/bioconda/bioconda-recipes/blob/25ee21573c577aa1ae899e0f7fbbc848d8a63865/recipes/mothur/meta.yaml#L14) of meta.yaml added during commit 25ee21573c577aa1ae899e0f7fbbc848d8a63865. There weren't any notes in the PR explaining why this change was made.

I've been looking into a similar issue with bowtie. From what I've gathered, this usually happens when there's an issue with the recipe that prevents the package from being built in the Bioconda pipeline, and the issue is either difficult or impossible to fix.

In my case, with bowtie, I suspect it is because it's meant to be built with GNU's `make` and `gcc` and macOS notoriously ships with Apple's own version (via XCode), or otherwise massively out-of-date BSD versions, of most Unix utilities including these. Configuring macOS to successfully use the GNU version of these utilities and their dependencies can be tricky business.

In your case, with mothur, I'm not seeing anything about their build instructions that immediately sticks out as an issue. I would recommend following [the instructions here for testing the recipe locally](https://bioconda.github.io/contributor/building-locally.html) and removing the `[osx]` selector on line 14. Give it a shot and see what it spits out. This isn't specifically related but I would also recommend taking a look at the end of Devon's initial comment on #32871 about using mambabuild. `bioconda-utils build` is more rigorous but it requires more setup and resources due to Docker and I found it sometimes hides useful error messages. With `conda mambabuild` you'll only be able to test osx builds but there's less hoops and weight.

Best of luck

**Comment by AlexTate** [comment]
@pschloss I observed the same. After looking into this a little further, it appears the pattern rule(s) on Makefile line 141 is being activated by lines 119-122 prior to the actual targets and prerequisite lists. This means that the uchime target isn't executed before compilation of mothur begins, and since build.sh passes -I. instead of -I./source due to the directory change in uchime, files in the root /source dir aren't compiled before the subdir sources which #include them.

The fix is actually frustratingly simple: pin `make` to 4.2.1 in the meta.yaml build requirements. All of this is due to backward-incompatible changes introduced in make 4.3 [which you can read about here](https://lists.gnu.org/archive/html/info-gnu/2020-01/msg00004.html). The only reason this has been an issue on osx and not linux is because 4.3 isn't available for linux on conda-forge, only osx.
