### ISSUE TITLE
Cython is not a real dependency of simlord, but build fails without

### ISSUE THREAD

**Issue by BiancaStoecker** [bioconda/bioconda-recipes#3427]
Simlord got updated from version 0.7.3 to version 1.0.1. In the program nothing about the dependencies changed, but for the new version the travis build fails, because cython is not a build dependency:

Errorlog: https://travis-ci.org/bioconda/bioconda-recipes/jobs/188872309#L625
Changes: https://github.com/bioconda/bioconda-recipes/pull/3377

Adding cython to the build dependencies fixed the problem, but it should not be there. So  @johanneskoester  asked me to open an issue.

Simlord is depending on dinopy, which currently has cython as dependency.

**Comment by johanneskoester** [comment]
I think the problem is that the dinopy setup.py specifies cython as a dependency. Apparently setuptools sees this and tries to install cython. Since setuptools based installations are forbidden in conda build scripts, the build fails.

From the sources of dinopy, it looks to me like cython is actually not a real dependency, because the c files are included (it is rather only a development dependency). Hence, I'd think that dropping the cython dependency in dinopy should fix the issue.

@HenningTimm, what do you think?

**Comment by HenningTimm** [comment]
That is correct. Cython is no longer a dependency since the last update, but unfortunately I forgot to remove it from the dependencies list. I will do so in the next update of dinopy (late January, early February). I thought that that might be the problem, but not exactly why.

Just for my understanding:
 - When installing simlord, dinopy is found as a dependency and is installed by conda
 - When installing dinopy, conda can not find any further dependencies and tries to start the installation of dinopy
 - Setuptools notices that Cython is not present, tries to install it and is stopped by conda, which results in the error we saw

Is that correct?

What threw us off was that the last recipe for simlord worked, but the new one did not, since I do not think I made any changes to dinopy in the meantime.

**Comment by johanneskoester** [comment]
I think the error is triggered by the setup.py of simlord. I also was not aware of that, but apparently it looks  into the dependencies of dinopy and tries to install cython because it is missing as it is not a runtime dependency of dinopy.

I also don't understand why it would have worked last time. Maybe a different setuptools version?

**Comment by epruesse** [comment]
outdated
