### ISSUE TITLE
nextstrain update

### ISSUE THREAD

**Issue by jcgrenier** [bioconda/bioconda-recipes#35054]
Hello dear developpers,

Thanks so much for putting together such a wonderful set of tools! We sometimes have issues with clusters on which we need to work on and this is definitely helping us resolving most of them.
I was wondering if it would be possible to update the Nextstrain docker container? I'm not sure if it's here that I can request such a demand. 
Thanks a lot for your help!

Jean-Christophe

**Comment by mfansler** [comment]
I believe we just need to bump [the version number on the metapackage](https://github.com/bioconda/bioconda-recipes/blob/8efec3dadf39713269b27f26932a3dbdaae7a719/recipes/nextstrain/meta.yaml#L3) to trigger a rebuild. @tsibley @huddlej can you confirm this?

**Comment by tsibley** [comment]
@mfansler Ah, the version number of the `nextstrain` metapackage in Bioconda is not related to Nextstrain's Docker container runtime image (`nextstrain/base` from https://github.com/nextstrain/docker-base).

@jcgrenier I think this request more appropriately belongs in https://github.com/nextstrain/docker-base or perhaps https://discussion.nextstrain.org depending on what exactly you're asking for. Is there some software in particular that needs updating inside the image? Or are you asking about how to update the image itself to a newer version? For what it's worth, if you're using the `nextstrain/base` Docker runtime image via the `nextstrain` command (the Nextstrain CLI), then you can see what version of the Docker runtime you have with `nextstrain version --verbose` and update it with `nextstrain update`. Latest is `nextstrain/base:build-20220523T233129Z`.

**Comment by mfansler** [comment]
@tsibley sorry, I was assuming this was about [the BioContainers version](https://biocontainers.pro/tools/nextstrain). I don't know the details, but I believe Bioconda triggers a Docker container build for every recipe. The `nextstrain` metapackage here hasn't been altered in 14 months, so its corresponding container hasn't been rebuilt.

@jcgrenier could you clarify what you were attempting to use?

**Comment by tsibley** [comment]
@mfansler Oh jeez, yeah, that could be the case! Thanks for pointing out the BioContainer. Do you know if periodically bumping the version of a metapackage is the only way to get it rebuilt with fresh deps? If so, I might be tempted to ditch the metapackage all together… we don't actually recommend installing using the metapackage in our docs since it had also caused some issues with `conda update` in the past.

**Comment by jcgrenier** [comment]
Hello everyone,
I was referring to the biocontainers themselves. My goal was to directly use the container on a cluster where I can't use bioconda to install it or update it. So, since I saw it wasn't updated since a long time and that Nextstrain team is actively updating their code, I was supposing that an update of the biocontainer could have been good to do.

Thanks a lot for help!

**Comment by tsibley** [comment]
@jcgrenier Ok, thanks for clarifying. We can look into doing version bumps to maintain the freshness of the BioContainer, but right now I'd recommend using our `docker.io/nextstrain/base` image instead of `quay.io/biocontainers/nextstrain`. It should contain all the same tools and is maintained and kept fresh directly by the Nextstrain team. It's the image we use for running our production analyses/builds, so it should generally always work. :-) You can either pin a specific `build-*` tag or use `latest`.

**Comment by jcgrenier** [comment]
Alright, thanks a lot for your help. I'll use the nextstrain base image on the docker page instead! Thanks for the explanations!

**Comment by tsibley** [comment]
@jcgrenier 👍🏻 If that doesn’t work out for some reason, please raise an issue in our image repo or post to discussion.nextstrain.org.
