### ISSUE TITLE
Update default compiler version for linux

### ISSUE THREAD

**Issue by matthdsm** [bioconda/bioconda-recipes#35525]
Is there a possibility to update the default compiler version for linux?
Apparently, the latest version of dragmap requires a newer version of gcc to build

https://github.com/Illumina/DRAGMAP/issues/34

Thanks

**Comment by matthdsm** [comment]
xref https://github.com/bioconda/bioconda-recipes/pull/35350

**Comment by matthdsm** [comment]
@bioconda/build-system, is there a way to fix this?

**Comment by daler** [comment]
@matthdsm super late reply, sorry. In general we use a channel-wide pinnings file that we share with conda-forge so that built packages can be mutually installed in the same environment and have ABI compatibility. But in cases like this you can use the local conda-build-config mechanism as an override. 

We use both the [conda-forge pinnings file](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml) as well as [our own](https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/bioconda_utils-conda_build_config.yaml).

Looks like the [conda-forge pinnings file](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml) has been using `cxx_compiler_version` 10 for almost a year now.

The spades recipe has an example of using a local [`conda_build_config.yaml`](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/spades/conda_build_config.yaml). This example had overridden to use version 9 at the time. So if the compiler version is the issue here, using the local pinnings override like the spades example is a mechanism to try to get it working.

**Comment by matthdsm** [comment]
Thanks for the reply!
I'll check it out.

M
