### ISSUE TITLE
Add sickle to bioconda

### ISSUE THREAD

**Issue by dridk** [bioconda/bioconda-recipes#3684]
https://github.com/najoshi/sickle

unfortunally, there is already a python package with the same name. How to manage this ? 
sickle is a c++ binary, and the python package is only a library. 

      conda install sickle-cpp ?

**Comment by bgruening** [comment]
sickle_trimming maybe?

**Comment by rvalieris** [comment]
sickle_trimming seems to be a good option, although I prefer using a dash (-), rather than a underscore.

language prefixes only makes sense to me on libraries, so I don't think it applies in this case, if you want to read more on the subject see https://github.com/conda-forge/conda-forge.github.io/issues/18

**Comment by johanneskoester** [comment]
To be consistent with other cases, maybe use a hyphen instead: sickle-trimming

**Comment by johanneskoester** [comment]
Actually, we have it already: [sickle-trim](http://bioconda.github.io/recipes/sickle-trim/README.html).
