### ISSUE TITLE
Packing failed in simulate-travis.py

### ISSUE THREAD

**Issue by sebastian-luna-valero** [bioconda/bioconda-recipes#3780]
Hello,

I have got the following error:
```
[Feb 13 08:56:13] DEBU Packing failed due to open build/dist/bin/vcfutils.pl: permission denied
[Feb 13 08:56:16] WARN Local execution errorred with error [open build/dist/bin/vcfutils.pl: permission denied], retrying with remote execution
```

when running `simulate-travis.py`. Here is more context:
```
[Feb 11 17:28:05] SOUT Extracting packages ...
[      COMPLETE      ]|##################################################| 100%                 |   0%
[Feb 11 17:28:05] SOUT Linking packages ...
[      COMPLETE      ]|##################################################| 100%                 |   0%
[Feb 11 17:28:34] DEBU Container [592b7974fb6d step-350eb3ea4e] completed with exit code [0] as expected
[Feb 11 17:28:34] DEBU Container [592b7974fb6d step-350eb3ea4e] removed
[Feb 11 17:28:34] STEP Wrap [build/dist] as [quay.io/biocontainers/ngseqbasic:2.0.1--0]
[Feb 11 17:28:34] DEBU Creating container [step-4effaa631c]
[Feb 11 17:28:34] DEBU Image [bgruening/busybox-bash:0.1] not present, pulling it
[Feb 11 17:28:34] DEBU Pull Image [bgruening/busybox-bash:0.1]
[Feb 11 17:28:36] PRGS {Pulling from bgruening/busybox-bash  {0 0} }
[Feb 11 17:28:36] PRGS {Already exists  {0 0} }
[Feb 11 17:28:36] PRGS {Already exists  {0 0} }
[Feb 11 17:28:36] PRGS {Already exists  {0 0} }
[Feb 11 17:28:36] PRGS {Already exists  {0 0} }
[Feb 11 17:28:36] PRGS {Already exists  {0 0} }
[Feb 11 17:28:36] PRGS {Already exists  {0 0} }
[Feb 11 17:28:36] PRGS {Already exists  {0 0} }
[Feb 11 17:28:36] PRGS {Already exists  {0 0} }
[Feb 11 17:28:36] PRGS {Already exists  {0 0} }
[Feb 11 17:28:36] PRGS {Digest: sha256:c84ec0edfba6dcb323eeed0806990024567b8119b8125542a2acdaf8abca743f  {0 0} }
[Feb 11 17:28:36] PRGS {Status: Downloaded newer image for bgruening/busybox-bash:0.1  {0 0} }
[Feb 11 17:28:38] DEBU Packing failed due to open build/dist/bin/vcfutils.pl: permission denied
[Feb 11 17:28:41] WARN Local execution errorred with error [open build/dist/bin/vcfutils.pl: permission denied], retrying with remote execution
[Feb 11 17:28:41] DEBU Creating container [step-d88ae3650a]
[Feb 11 17:28:41] DEBU Image [involucro/tool:latest] not present, pulling it
[Feb 11 17:28:41] DEBU Pull Image [involucro/tool:latest]
[Feb 11 17:28:42] PRGS {Pulling from involucro/tool  {0 0} }
[Feb 11 17:28:42] PRGS {Pulling fs layer  {0 0} }
```

Is this expected?

When testing my new recipe on this container, `$SRC_DIR` is empty and I don't know whether the problem above is related or not.

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
It looks like `$SRC_DIR` is not exported to the container?

I was expecting `$SRC_DIR` to have the same behaviour as explained here:
https://conda.io/docs/building/environment-vars.html

How can I get to the source code of my recipe to run tests?

Best regards,
Sebastian

**Comment by daler** [comment]
`$SRC_DIR` is provided by conda when building; simulate-travis.py doesn't have much to do with it. The error you're seeing is in mulled-build testing step. The mulled-build container only ever sees the built package -- not even conda is in that container. This is by design because it's the most isolated way of testing and catches lots of errors that would otherwise go unnoticed.

If you want something to be seen by the mulled-build container, it needs to be in the built package, which means copying things over from `$SRC_DIR` in the `build.sh` script of the recipe.

**Comment by sebastian-luna-valero** [comment]
Many thanks @daler !

**Comment by sebastian-luna-valero** [comment]
Just wanted to add that if you do `conda build myrecipe/`, `$SRC_DIR` will be available in the test section. That's why I was initially confused and may cause others to be confused as well when moving conda recipes to bioconda.

**Comment by daler** [comment]
Yep, and based on your log, your conda tests are working fine. It's the second, more stringent mulled-build testing step that fails. 

Some more details that might help clarify: 

1. conda-build runs, in a `condaforge/linux-anvil` docker container. That's the only time `$SRC_DIR` is available.
2. After the conda-build test passes, we extract the tests from the recipe (it happens [here](https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/pkg_test.py#L15))
3. We unpack the newly-created-by-conda-build `.tar.bz2` package into a different, minimal container that doesn't have conda.
4. The collected tests are then run in the container.

So since conda is the thing responsible for `$SRC_DIR` and conda is not even installed in the container, we can't rely on any conda-specific env vars in tests.

Once I finally get time to write the build system docs I'll definitely add this info to prevent any confusion in the future.

**Comment by sebastian-luna-valero** [comment]
Thank you again @daler , IMHO it's a fantastic approach ;)
