### ISSUE TITLE
Add some R packages to bioconda recipes

### ISSUE THREAD

**Issue by Kur1sutaru** [bioconda/bioconda-recipes#38297]
Hi folks, I need to install with mamba the following packages:
doublet-finder https://github.com/chris-mcginnis-ucsf/DoubletFinder
seurat-disk https://github.com/mojaveazure/seurat-disk
dropkick https://github.com/KenLauLab/dropkick

If you can put this r packages on bioconda, to be easy installed by mamba, I appreciate that!
Thank you so much for your amazing work! 😄

**Comment by mfansler** [comment]
The `SeuratDisk` package is already available on Conda Forge:

```bash
mamba install -c conda-forge r-seuratdisk
```

Since `dropkick` is on PyPI, with no `bioconda` requirements, we can add that to `conda-forge`.

As for `DoubletFinder`, at minimum we would want a GitHub repository that generates Releases. Preferable would be having that package on CRAN. Maybe ask the author(s) to consider generating a GitHub Release or encourage them to get it on CRAN.

**Comment by Kur1sutaru** [comment]
Thank you!

**Comment by mfansler** [comment]
Hmm...hit some `numba` import issues with [the `dropick` package build](https://github.com/conda-forge/staged-recipes/pull/21576). Not sure I'll get around to troubleshooting that for a bit. 

In the meantime, note that Conda environments can be defined with `pip` dependencies via YAML. Not preferred, but still effectively reproducible.
