### ISSUE TITLE
Update the dependencies of ensembl vep

### ISSUE THREAD

**Issue by user-tq** [bioconda/bioconda-recipes#38692]
I try install   ensembl-vep
```
mamba install  ensembl-vep=108.2  -c bioconda 
```
The installation is OK, but when I want to run vep,it return erro
```
Compress::Raw::Zlib version 2.201 required--this is only version 2.105 at /root/miniconda3/lib/perl5/site_perl/Compress/Zlib.pm line 11
```
The latest version of ```Compression:: Raw:: ZLib``` in Bioconda is [2.105](https://anaconda.org/bioconda/perl-compress-raw-zlib) but the newest is [2.202](https://metacpan.org/pod/Compress::Raw::Zlib)
Maybe Conda's inspector should have found this

**Comment by daler** [comment]
@user-tq I'm unable to reproduce. What happens if you set up channels according to the bioconda docs? https://bioconda.github.io/ shows that you need to add the conda-forge channel as priority, which should allow the solver to pick up 2.202 from https://anaconda.org/conda-forge/perl-compress-raw-zlib.

If it still doesn't work, please paste the results of `conda config --show` for troubleshooting.

**Comment by yachenhu** [comment]
@daler is right. I solved the problem by adding the `--strict-channel-priority` option to the command. My command is
```
$ mamba create -n vep --strict-channel-priority -c conda-forge -c bioconda ensembl-vep=108.2
```
