### ISSUE TITLE
Is it possible to submit a package one of whose dependencies is proprietary into bioconda?

### ISSUE THREAD

**Issue by CicoZhang** [bioconda/bioconda-recipes#3921]
As mentioned in the title, the proprietary dependency is IBM's CPlex, which I cannot disseminate freely. I don't know whether I can submit such a package into bioconda, since lack of this dependency will fail travis and users with licenses need to install the dependency themselves before using this package.

**Comment by tomkinsc** [comment]
Since bioconda recipe tests are basic and mainly check executability, are you able to create a test that checks the functions of the package that do not rely on CPlex? Even a simple: `<package> -h` would be enough.

We do have a number of license-encumbered software packages in bioconda, including [GATK](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/gatk) and [Novoalign](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/novoalign). In each case we have worked within their license restrictions. Novoalign can be distributed in compiled form, so we do that. For GATK, redistribution is prohibited, so we stub out a recipe that includes a `post-link.sh` script to alert the user that they will need to call `gatk-register` which will copy an already-licensed instance of GATK into the active conda environment. Would a GATK-like approach work for your package or its CPlex dependency?

**Comment by CicoZhang** [comment]
Hi, @tomkinsc Thank you for the reply. 
 <package> -h is possible. 

I have the academic license of CPlex.

The codes are in C++ and CPlex is needed for compiling the codes. After the compilation, CPlex is not needed.

I am not quite sure whether it is OK that the compiled form is made available in Bioconda. 

> IBM grants you a nonexclusive, nontransferable license to use Eligible Resources solely for instruction and learning, as well as noncommercial research at the Institution. This use includes the design, development and testing of applications, hardware or virtual environments created by you. **Eligible Resources cannot be used in production environments**. Only Registered Educators may make copies, including backup copies, to support the level of use authorized, provided that the copyright notices and any other legends of ownership are reproduced on each copy or partial copy of the Eligible Resources. Registered Educators may use Eligible Resources and distribute them only to Registered Students enrolled in specific courses/programs requiring access.
> Eligible Resources may not be 1) used, copied, modified, or distributed except as provided in this Agreement; 2) reverse assembled, reverse compiled, or otherwise translated, except as specifically permitted by law without the possibility of contractual waiver; 3) sublicensed, rented, or leased; 4) have Internet "links" to or from the offering for third parties to access. No Eligible Resource may be used for commercial or administrative purposes. In addition, Eligible Resources may not be used for noncredit courses which do not lead to nationally recognized qualifications or levels of academic achievement unless indicated to the contrary by IBM on the hub catalog at ibm.biz/ibmonhub2. IBM shall have no responsibility for any costs required for certification examinations and training for any Registered Educator and Registered Students.
>

**Comment by tomkinsc** [comment]
It doesn't sound like the CPlex license will allow redistribution through bioconda, but you could email the development team at IBM and ask.

**Comment by CicoZhang** [comment]
@tomkinsc There is a community version of CPLEX, which is very limited in capacity but free to use. After contacting IBM, I plan to use the community version.
