### ISSUE TITLE
Are forked tools are supported?

### ISSUE THREAD

**Issue by ndaniel** [bioconda/bioconda-recipes#4002]
Are forked tools supported in bioconda? If yes, how? Is there any documentation regarding forked tools in bioconda?

**Comment by bgruening** [comment]
@ndaniel There is now guideline and yes it is supported. Look at graphicsmagick, which is a fork of imagemagick: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/graphicsmagick/1.3.20/meta.yaml

They changed the name, they maintain the fork and offer support. It is just an other package. Please join us on https://gitter.im/bioconda/Lobby. 
And btw. you closed your PR and discussion was not even midway ;)

**Comment by ndaniel** [comment]
@bgruening 
You mentioned guideline and support. Please, could you point me to the guideline? I could not find any pointer in your post.

Regarding closing the PR is because I found personally the bioconda community very *unwelcoming* (see your own post which contains that word ***hate**!

**Comment by bgruening** [comment]
Ah you mean me. I was searching for the word `hate` int your seqtk PR 2 years back. Yes I hate when this happens -- this means: That someone is forced to `fork` a project because patches are not accepted.

Everything else is your Interpretation.

Quoting myself:
> `But we do support forks if there is a valid reason. I'm not even opposed to merge this PR but a little bit more poking and trying to get this upstream would be great.`

Above is the imagemagick example. So yes we do accept PR from forked projects. I never mentioned the work guideline. And imho there is no guideline. We do support all kinds of packages but we do ask for valid reasons to accept forks. And again this was an ongoing discussion, you closed the PR.

Quoting myself again:
>`I'm not even opposed to merge this PR`

Splitting the discussion above 3 threads didn't help either. We were just asking to explain why this fork is needed and @yhoogstrate also added a few other reasons, next to mine.

> Regarding closing the PR is because I found personally the bioconda community very unwelcoming (see your own post which contains that word *hate!

This is very sad and you are the first one that tell me that. But maybe it's just that you misinterpreted that I mean this my sentence. Sorry to be not clear enough.

**Comment by ndaniel** [comment]
@bgruening 

You wrote this:
> @ndaniel There is now guideline and yes it is supported. Look at graphicsmagick, which is a fork of imagemagick: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/graphicsmagick/1.3.20/meta.yaml

 Please, could you point me to the guideline? I could not find any pointer in your post.

You also wrote:
> I never mentioned the work guideline. And imho there is no guideline. 

So, is there guideline for forks in bioconda?

> Everything else is your Interpretation.
>...
> But maybe it's just that you misinterpreted that I mean this my sentence. 

This is very unwelcoming for someone who just arrived to bioconda few days ago. According to you if someone gets offended it is the fault of the victim and not the fault of the offender because the victim has misinterpreted the meaning!

**Comment by bgruening** [comment]
>> @ndaniel There is now guideline and yes it is supported. Look at graphicsmagick, which is a fork of imagemagick: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/graphicsmagick/1.3.20/meta.yaml

 See and here we go. `s/now/no/g`. Sorry for that.

You also wrote:
> I never mentioned the work guideline. And imho there is no guideline. 

So, is there guideline for forked tools in bioconda?

*No.* Not that I know of.

>> Everything else is your Interpretation.
>>...
>> But maybe it's just that you misinterpreted that I mean this my sentence. 

>This is very unwelcoming for someone who just arrived to bioconda few days ago. According to you if someone gets offended it is the fault of the victim and not the fault of the offender because the victim has misinterpreted the meaning! 

Victim, offender? Sorry, if you feel offended. Simply ask next time before you assume that everyone whats something bad. I don't, and nobody else wanted to, I'm pretty sure. 
I guess my mistake is that I by default assume a friendly reaction and I should be more carefully in what I and how this can be misinterpreted. `I hate when this happens.` Is a very nice example and I should be more concrete before I write this to not offend anyone.
Please just respond to technical questions and ignore everything else from me.

**Comment by daler** [comment]
We have no guidelines for forks, but this is as good a time as any to kick around ideas on what those guidelines might be.

For example, in this case, the issue is that changes in the fork didn't make it into upstream, and I agree with Bjoern that this is annoying. Should we ask for a "failed best effort" of getting changes into upstream? What would this be? Should the burden be on the upstream author to show that the merge is not possible, or the fork author to show benefits of the merge? Who decides?

Then if it doesn't get into upstream, how should we name packages? `*-fork` seems too generic. What if there are multiple forks? I think `*-fork2` would be even worse.

What classes of forks are there? Here the fork is kind of tied to fusioncatcher, so should fusioncatcher be in the name? Maybe there are other forks that are not tied to a particular tool. Should forks instead be indicated in version strings, with a `post` or `modified` tag to indicate which version they were branched off of?

Some forks could be minor patches on upstream; other could be major overhauls. Is there a reason for this to be indicated somehow? At what point does a fork become its own package?

Anyway, lots of things to think about and it's a tricky question which is probably why we don't have guidelines on this yet.

**Comment by bgruening** [comment]
This is a very tricky question and the guideline should probably depend on a lot of factors. I think we should highly advertise to get patches upstream as a general remark. A real fork should imho have it's own name so that it did not clash with the original development. Names like `*-fork` is imho not a good idea as this is does not help the users to choose between a specific package and is confusing.

In the special case of @ndaniel maybe the easiest way is to not include the fork at all but ship/compile it as part of his real tool - still renaming needs to happen at some point to be able to mix packages. But maybe a simple `mv seqtk seqtk_foo` will work.

**Comment by bgruening** [comment]
@ndaniel is this still an issue for you? Please feel free to reopen this issue.
