### ISSUE TITLE
Cannot find and apply a recipe's new patch file

### ISSUE THREAD

**Issue by ccwang002** [bioconda/bioconda-recipes#4074]
I was trying to update the recipe for methylKit to make it compiled on OSX. I am currently stuck at the error that I cannot apply my new patch. The error is shown below:

```
Source cache directory is: /Users/liang/miniconda3/conda-bld/src_cache
Found source in cache: methylKit_1.0.0.tar.gz
Extracting download
Applying patch: '/Users/liang/tools/bioconda-recipes/recipes/bioconductor-methylkit/rpath.patch'
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was:
Command '['/usr/bin/patch', '-p0', '-i', '/Users/liang/tools/bioconda-recipes/recipes/bioconductor-methylkit/rpath.patch']' returned non-zero
...
```

the relevant part of my `meta.yaml` is:

```yaml
source:
  fn: methylKit_1.0.0.tar.gz
  url: https://bioarchive.galaxyproject.org/methylKit_1.0.0.tar.gz
  md5: 3612ce6bf0b748d8869a4a16c57265dc
  patches: # [osx]
    - rpath.patch # [osx]
```

and my patch header is:

```patch
--- src/Makevars	2016-10-12 18:25:26.000000000 -0500
+++ src/Makevars	2017-03-09 01:00:27.000000000 -0600
@@ -1,6 +1,9 @@
```

Patch and new recipe can be found at [my working branch of `recipes/bioconductor-methylkit/`](https://github.com/ccwang002/bioconda-recipes/tree/bioconductor-methylkit/recipes/bioconductor-methylkit).  I tried removing `src/` and it still failed. 

Can someone point out the correct way how to write a new patch? Thanks.

**Comment by acaprez** [comment]
There are a couple of tab characters in the original `Makevars` file at the end of the `CXX?=g++-4.8` line that aren't in the patch file, so that's why it's rejecting it.  If you look at both files in vim after running `set list` to show non-printing characters you'll see the difference.  The line in the patch file should look like `-CXX?=g++-4.8^I^I$`; instead it's `-CXX?=g++-4.8$`.   I've had that happen before when copy & pasting patch files as my iTerm is set to automatically replace tabs with spaces.

**Comment by ccwang002** [comment]
Thank you so much! I think this is the exact reason why my patch kept failing. My path specified in the patch is correct but my content is not. Now I know the direction to solve the issue.
