### ISSUE TITLE
Nextstrain-cli artefact not available after PR merged, despite later PRs resulting in updates

### ISSUE THREAD

**Issue by corneliusroemer** [bioconda/bioconda-recipes#41223]
For some reason, nextstrain-cli does not seem to be updated on the index, despite being merged before 3 other PRs that have since become available on the index.

Nextstrain CLI PR: #41189 

Later PRs: #41190, #41213, #41218 

I merged the augur PR directly after the nextstrain cli PR, within less than a minute. Maybe that's why something went wrong? @dpryan79 

<img width="857" alt="image" src="https://github.com/bioconda/bioconda-recipes/assets/25161793/cb2ba732-aefe-47fe-be3c-4ff2e63ca1c4">

**Comment by joverlee521** [comment]
I was curious so I looked into the [Azure pipeline run](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=33952&view=results) for the nextstrain-cli merge.

The [logs](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=33952&view=logs&j=9d4cda30-b5f2-5e95-e642-70fa3f43a691&t=3b24cbaa-a0db-5c6a-6d4a-e4148972f28a&l=34) show that it processed the recipe for Augur instead of the nextstrain-cli. My guess is #41190 was merged too soon after #41189 so by the time the Azure pipeline started, it only saw the Augur recipe change.

**Comment by dpryan79** [comment]
It's exactly as @joverlee521 suspected. I was silly when I was trying to get this to work again yesterday and used HEAD~1 and HEAD for the diff to determine what to build. That only works if it clones the repos given the hash of the commit that triggers the CI run. It turns out it git clones master, so if multiple branches get merged at about the same time that only the last one will get built (at least most of the time). I'll work on fixing that now.

**Comment by dpryan79** [comment]
This should be fixed now.

**Comment by corneliusroemer** [comment]
Thanks @joverlee521 and @dpryan79 :)

**Comment by joverlee521** [comment]
The missed update for nextstrain-cli should get caught by tonight's scheduled nightly upload job?

**Comment by dpryan79** [comment]
It's there now finally. I hate transitioning CI systems.
