### ISSUE TITLE
Problem creating a conda package for TSEBRA

### ISSUE THREAD

**Issue by rlibouba** [bioconda/bioconda-recipes#42162]
Hello, I'm having difficulties creating the conda package for TSEBRA. During the package packaging process, it seems that there are no files or folders to include. 
Here's the PR link: https://github.com/bioconda/bioconda-recipes/pull/41919

Thank you in advance for any reply.

**Comment by kbseah** [comment]
Hello, thanks for the contribution!

The script can't be found under `./bin/tsebra` as given in the test command, because you need to include a `build.sh` script to move the files to the Conda environment path. Have a look at the `build.sh` script of the `braker2` recipe for some ideas on how that could be done.

By the way your fork of the `bioconda-recipes` repo is quite old, you might want to update and rebase your commits.

**Comment by rlibouba** [comment]
Hello, thanks for your response.

I have added the build.sh script. However, I don't understand why during the packaging process, the tseabra.py script is not found. While testing locally, I checked that copying files/folders had worked, as well as the rights on the tseabra.py script. All is good, but it fails.
