### ISSUE TITLE
remove from repository

### ISSUE THREAD

**Issue by CatarinaCarolina** [bioconda/bioconda-recipes#42821]
Could you remove the package https://anaconda.org/bioconda/bigscape

It was not generated by BiG-SCAPE developers (https://github.com/medema-group/BiG-SCAPE) and it leads to a faulty installation/environment.

**Comment by rpetit3** [comment]
Hi @CatarinaCarolina,

Apologies for the slow response! We have a few options here:

1. blacklist bigscape so that future releases do not have future releases to not have automatic PRs created
2. work together to fix the current recipe

For the first option, this will not remove existing versions of bigscape available from Bioconda. It will only prevent new releases from being added. Users will still be able to install bigscape through conda, but only the older versions which may or may not create more issues for you in the future.

The second option, we can work together to fix the recipe as suggested here https://github.com/medema-group/BiG-SCAPE/issues/23#issuecomment-1504801954 

Ultimately, I'll let you and your team decide on how you would like to proceed. However, if you are OK with it, would you and your team OK if I made an attempt to fix this recipe for you?

Thank you @CatarinaCarolina , and again apologies for a really slow response!
Robert

**Comment by pettyalex** [comment]
I submitted a PR to fix bigscape's distribution, following those suggestions: https://github.com/medema-group/BiG-SCAPE/pull/76
