### ISSUE TITLE
mummerplot 

### ISSUE THREAD

**Issue by jingjin0322** [bioconda/bioconda-recipes#4319]
Hi,
I had a problem when I was trying to run the command mummerplot out.ntref. It says can't use 'defined(%hash)'  (maybe you should just omit the defined()?) at /usr/bin/mummerplot line 884. Seems someone had same problem before, but still I was not able to solve the problem by taking a look at the comments in the previous post. Really hope someone could help me out. I will really appreciate it. (I have perl 5.22.1 in my ubuntun)

Thanks,
Jing

**Comment by tseemann** [comment]
This is not an error, just a Perl warning about old syntax.  The code should still work?

**Comment by rvalieris** [comment]
The problem is that defined(%hash) has been upgraded to a fatal error in recent versions of perl, as a stop gap solution we do a hotfix during the build of the mummer package, see https://github.com/bioconda/bioconda-recipes/blob/master/recipes/mummer/build.sh#L40.

However it seems you are not using the mummerplot installed by bioconda, since program path in the error is  `/usr/bin/mummerplot`
