### ISSUE TITLE
ensembl-vep package perl lookup issue

### ISSUE THREAD

**Issue by nilesh-tawari** [bioconda/bioconda-recipes#4390]
@matthdsm
Installed ensembl-vep using conda but while running command "vep" error occurs, 
`"perl: symbol lookup error: /lib/perl5/5.10.1/auto/Cwd/Cwd.so: undefined symbol: Perl_Istack_sp_ptr"`
Any work around? thanks

**Comment by matthdsm** [comment]
Hi @nilesh-tawari 
It seems to me that you're using the wrong perl interpreter for the vep executable. the conda vep version is built with the bioconda-perl (v5.20) while you're using the libraries for your system installed perl (v5.10), which are incompatible.

quick google search [result](http://stackoverflow.com/questions/32065108/redhat-perl-5-10-1-getting-error-symbol-lookup-errorauto-math-pari-pari-so-un).

Perhaps @bioconda/perl can help you with this.

Cheers 
M

**Comment by bgruening** [comment]
@nilesh-tawari you are using your system perl package and not the conda perl version. Can you please try to install it into a isolated environment via `conda create -n vep ensembl-vep`

**Comment by nilesh-tawari** [comment]
@matthdsm 
Yes, the problem is incompatibility in perl versions. 
@bgruening
I have created a separate environment installed vep in that. Below is my perl version, 

```
(ensembl-vep) [nilit@n126]$ which perl
~/miniconda3/envs/ensembl-vep/bin/perl
(ensembl-vep) [nilit@n126]$ perl -v
This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi
```
If i use vep command in the condas environment i get error,
`perl: symbol lookup error: /mnt/software/lib/perl5/5.10.1/auto/Cwd/Cwd.so: undefined symbol: Perl_Istack_sp_ptr`

But if i use system perl (which is perl v5.10.1) to launch VEP in condas environment, VEP works fine. So I think the conda vep version is built with the bioconda-perl (v5.10) but its installed with v5.22 in conda dependency by-default that is the issue. 
Any way to fix this? Please let me know if you need additional information.
Thanks.

**Comment by bgruening** [comment]
@nilesh-tawari `/mnt/software/lib/perl5/5.10.1/auto/Cwd` this is not your conda perl isn't it? I don't understand why this is used. Do you have a PERL path set, or something similar?

**Comment by jerowe** [comment]
Can you run 'which perl' with you conda env activated and see how it looks?

**Comment by nilesh-tawari** [comment]
@jerowe 
`(ensembl-vep) [nilit@n126]$ which perl
~/miniconda3/envs/ensembl-vep/bin/perl`

**Comment by nilesh-tawari** [comment]
@bgruening 
Yes, `/mnt/software/lib/perl5/5.10.1/auto/Cwd` is not conda perl. Let me check why it is being used.

**Comment by jerowe** [comment]
Did you do 'which perl' and then hit enter, or 'which perl ~/miniconda3/envs/ensembl-vep/bin/perl' ?

**Comment by nilesh-tawari** [comment]
@jerowe I did which perl' and then hit enter

**Comment by jerowe** [comment]
Ah ok. ;-)

I'm not sure why it is doing this. It sounds to me like one of these problems where some script calls some script that calls some other script, and one of those may be calling a different perl?

Could you 'echo $PATH' ?

**Comment by jerowe** [comment]
This software has a ~1700 line Install file.

**Comment by bow** [comment]
I recently stumbled on something similar, but in my case this manifested simply as a segmentation error (which was, eh, very helpful).

Anyway, I finally tracked down the issue to Perl loading the wrong module (despite using the correct conda-installed executable). You can check this with `perl -V`. My guess is that somewhere in your environment, the `PERL5LIB` value is set (you should see this as one or more paths in your `@INC` entry when you do `perl -V`. In other words, if your `@INC` entries do not point to any conda-related paths, this could be the cause.

How could this be? If the module you are loading (in this case `Cwd`) exist in any of those paths, it will load it first. Some of the modules can be compiled C object files, which is incompatible with your active perl, hence the error.

In my case, the fix is simply to prepend `PERL5LIB=""` in front of the executable, which disables the interfering `PERL5LIB` and makes perl look for modules in the correct conda paths.

On a related note, aside from modifying the `activate` script of conda, perhaps it is possible to unset `PERL5LIB` for perl-related executables? I imagine this could be a common error ...

**Comment by bgruening** [comment]
@nilesh-tawari can you check the hints from @bow please?

**Comment by GuyAllard** [comment]
I have just encountered this issue.
Trying to run vep results in a segmentation fault.

Following the advice from @bow, if I run it using:
PERL5LIB="";vep
then everything is OK.

**Comment by michaelgreenburg** [comment]
Sorry to resurrect an old thread, but I had a similar issue (I was trying to use maker) and figured I would share my fix. I found out from [this stack overflow question](https://stackoverflow.com/questions/34606196/create-a-post-activate-script-in-conda) that scripts in ${CONDA_PREFIX}/etc/conda/activate.d/ and .../deactivate.d will run on activation and deactivation of the environment. Since the presence of the PERL5LIB environment variable creates issues, I store and clear it on activation of the environment, then restore it on deactivation. I used the following two files:

~/.conda/envs/envname/etc/conda/activate.d/drop_perl5lib.sh:
```
#!/bin/bash
# PERL5LIB is annoying in this environment; save it for later, then drop it
echo $PERL5LIB > ~/.perl5lib
PERL5LIB=""
```
~/.conda/envs/envname/etc/conda/deactivate.d/restore_perl5lib.sh:
```
#!/bin/bash
# Restore PERL5LIB upon deactivation of this environment
export PERL5LIB=`cat ~/.perl5lib`
rm ~/.perl5lib
```

Now, PERL5LIB is empty whenever I am in this environment--which allows maker to run without a hitch.

The error I got when I tried to run `maker` before getting rid of PERL5LIB (so that other Googlers can find this):
```
~/.conda/envs/envname/bin/perl: symbol lookup error: /path/to/perl5/lib/perl5/x86_64-linux-thread-multi/auto/List/MoreUtils/MoreUtils.so: undefined symbol: Perl_Gthr_key_ptr
```

**Comment by whiteorchid** [comment]
you should first unset PERL5LIB, and export PERL5LIB=$PERL5LIB:/the/path/to/your/perl in this command;
 if you use multi thread, 
that is :
unset PERL5LIB
export PERL5LIB=$PERL5LIB:/perl-5.24.1/lib/5.24.1/x86_64-linux-thread-multi/
export PERL5LIB=$PERL5LIB:/perl-5.24.1/lib

**Comment by bgruening** [comment]
@michaelgreenburg @whiteorchid thanks a lot for sharing your workaround.

Please feel free to post an issue upstream. https://github.com/conda-forge/perl-feedstock/issues/

Our main problem is that we need someone who steps up in maintaining perl and its ecosystem. We know what needs to be done, but we don't have so much perl experts in the conda community :(
