### ISSUE TITLE
Conda not found error for Vcfsim

### ISSUE THREAD

**Issue by Pie115** [bioconda/bioconda-recipes#45384]
Hello, I have package on bioconda:
https://bioconda.github.io/recipes/vcfsim/README.html?highlight=vcfsim#package-package%20&#x27;vcfsim&#x27;

The page was built correctly, and we successfully pushed it to bioconda. However, when we go to the page on bioconda, it has a conda not found tag at the top. Every time I try to install it using conda, it doesn't work, and says the package isn't found/doesn't exist. Any help would be greatly appreciated!

Thank you so much,
Paimon Goulart

**Comment by aliciaaevans** [comment]
The problem is `skip: True`. This tell conda to skip the build. Usually it's used for skipping certain architectures, such as `skip: True # [osx]`, so that's why there is no error. The Azure runs from October were cleaned up, but my guess is that it never actually built after the linting succeeded.

Go ahead and open a PR to remove the skip (or add the comment to selectively skip). You shouldn't need to bump the build number since it doesn't exist in the channel yet.
