### ISSUE TITLE
Mac cannot download any packages. 

### ISSUE THREAD

**Issue by transposons-thesis** [bioconda/bioconda-recipes#45586]
Dear all, 

Thank you for the help but I am unable to download some packages. Packages like Numpy, Pandas are all good but I need the following for a project:
     1. bowtie2
     2. SRA tools 
     3. bedtools
    
When I tried to download it I get the following error: "PackagesNotFoundError: The following packages are not available from current channels:"
- I added Bioconda, I even tried with other channels but none of it works. I have no idea what to do, I am very confused. I tried to download them in a hundred ways. 

This is my laptop: MacBook Air M2 2022
And I am using miniconda. I have just downloaded it so there should be no issues and I am working in the following environment: 

     active environment : CHIP
    active env location : /Users/frivetti/miniconda3/envs/CHIP
            shell level : 2
       user config file : /Users/frivetti/.condarc
 populated config files : /Users/frivetti/.condarc
          conda version : 24.1.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m2
                          __conda=24.1.0=0
                          __osx=13.4=0
                          __unix=0=0
       base environment : /Users/frivetti/miniconda3  (writable)
      conda av data dir : /Users/frivetti/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/osx-arm64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/frivetti/miniconda3/pkgs
                          /Users/frivetti/.conda/pkgs
       envs directories : /Users/frivetti/miniconda3/envs
                          /Users/frivetti/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.1.0 requests/2.31.0 CPython/3.11.5 Darwin/22.5.0 OSX/13.4 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False

Thank you

**Comment by mfansler** [comment]
There are two problems:

1. Bioconda does not support **osx-arm64** natively. Rather, you must emulate by using the **osx-64** subdirectory.
2. Bioconda builds primarily against Conda Forge, therefore, `conda-forge` must be the top priority channel (not `defaults`/`main`/`anaconda`).

If you are just starting off a fresh Conda installation and you expect to often require Bioconda, I would strongly recommend uninstalling Miniconda **osx-arm64** and instead install Miniforge **osx-64**. This will make `conda-forge` the default channel and **osx-64** the default subdirectory.

Otherwise, you have to manually override subdirs, as shown in [this StackOverflow post](https://stackoverflow.com/a/72679307/570918).

**Comment by biogabriel7** [comment]
@mfansler I tried doing this, so I installed Homebrew, I downloaded wget to add Mini-Forge but when I tried 
$ wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-x86_64.sh
$ bash Miniforge3-MacOSX-x86_64.sh 

I received this
$ Miniforge3-MacOSX-x86_64.sh: line 313: /Users/gabrielduarte/miniforge3/conda.exe: Bad CPU type in executable

So I'm thinking it's basically a problem with not having Rosetta since it's a brand new Mac. 

Do you have any idea how to solve this?
Thanks!

**Comment by mfansler** [comment]
Have you tried [installing Rosetta](https://support.apple.com/en-us/HT211861)?

I don't recall having to do this, but perhaps need to run the installer in x86_64 mode, i.e.,

```bash
arch -x86_64 /bin/zsh -i Miniforge3-MacOSX-x86_64.sh
```

Note that `zsh` is the default shell in macOS, not `bash`.

**Comment by biogabriel7** [comment]
Yep, it was that easy. I just downloaded Zoom and automatically installed Rosetta, deleted the files it created when using $wget on my directory and did everything again. Running smoothly now! Thanks for the answer :)

**Comment by peterjc** [comment]
Closing issue as the original poster was able to get things working with Rosetta, and long term BioConda does now support osx-arm64 but this must be added to each package individually.
