### ISSUE TITLE
no image on quay.io for robust_bias_aware

### ISSUE THREAD

**Issue by lspindler2509** [bioconda/bioconda-recipes#46769]
My recipe for robust-bias-aware was recently (over a week ago) merged into main and hence, all tests passed. 
Nevertheless, there is still no image uploaded on quay.io, the folder for it exists but there is no image in tags.

Why could that be? If there occurred any errors during the image creation, where could I find an error log or something similar?

The package is installable via conda install.

here is the merged PR:
https://github.com/bioconda/bioconda-recipes/pull/46056

Thanks already for any help!

**Comment by aliciaaevans** [comment]
Hi @lspindler2509, unfortunately, the build logs have since been cleaned up so I'm not sure what happened since the upload job appears to have succeeded. I suggest creating a new PR to bump the build number in meta.yaml. Then after those PR checks build, get the artifacts with BiocondaBot (I see you tried on the original PR, but I guess it couldn't find the build at that point.) If everything checks out with the image that is built, the PR can be merged to master and we can take a look at the logs on Azure for the upload. Feel free to add me as a reviewer on the new PR.

**Comment by aliciaaevans** [comment]
Fixed by https://github.com/bioconda/bioconda-recipes/pull/47309
