### ISSUE TITLE
Avoiding repetition of the JAVA wrapper script

### ISSUE THREAD

**Issue by peterjc** [bioconda/bioconda-recipes#4775]
When a JAVA package does not supply a shell script or equivalent, and the authors expect you to use ``java -jar ....`` the BioConda guidelines https://bioconda.github.io/guidelines.html#java say to add a wrapper script based on https://github.com/bioconda/bioconda-recipes/blob/master/recipes/peptide-shaker/peptide-shaker.py

Can and should we avoid the code duplication in this non-trivial Java wrapper script by using a central script, perhaps via a symlink in the recipe - or autogenerated by the recipe from a central BioConda template?

**Comment by bgruening** [comment]
There is one line in each wrapper that needs to be changed, so it is not as easy, but still possible. Even better if we can create a package for it, isn't it?

**Comment by peterjc** [comment]
I'll leave the technical side to the team's judgement - but the current repetition seems likely to cause trouble when we need to update all the Java wrappers at some point.

**Comment by daler** [comment]
For java packages we could require an `extra: jarfile:` key in their `meta.yaml`. Then we could have a tool in `bioconda-utils` that, given a `meta.yaml` file, builds the wrapper. That would keep the wrapper and meta.yaml tightly coupled.

However, the jarfile depends on exactly what's happening in `build.sh`. For example, for peptide-shaker, the `PeptideShaker-1.16.4.jar` is unzipped from the source. So definitely still some room for error, and I don't see a way to tightly couple `build.sh` with `meta.yaml` and the wrapper. 

The effort to copy and edit a line is maybe less than setting the proper `extra:jarfile` and running an extra tool, but it would save in updating wrappers. That said, since all wrappers presumably only differ by their `jar_file = ...` line, it would be just as easy to retrofit wrappers by extracting that line and sticking it in an updated wrapper. So currently I think I'm on the fence with respect to cost/benefit of changing the current setup.

**Comment by rvalieris** [comment]
maybe we could have a java-wrapper-generator tool, and each recipe would call this tool inside `build.sh` to generate its own wrapper.

to update the wrapper we could automatically trigger new rebuilds to all recipes that depends on java-wrapper-generator.

**Comment by bgruening** [comment]
I like what @daler said and people seem to be fine with the wrapper at the moment.

If we change the wrapper we, either way, need to rebuild the package. So there is not much of a different (if we not create its own package).

Should we leave this issue open or can we close it.

**Comment by peterjc** [comment]
The fact that there has been little comment suggests it hasn't been a big issue for packaging Java tools, which is reassuring. It seems the current situation is acceptable - I would OK with closing this issue.

**Comment by bgruening** [comment]
Thanks Peter!

**Comment by bgruening** [comment]
We are trying to clean our issues and PRs during the Cofest today :)
