### ISSUE TITLE
Out of credits at CircleCI

### ISSUE THREAD

**Issue by martin-g** [bioconda/bioconda-recipes#50622]
https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes says:
```
Your organization is out of credits. Next free refill is on October 1, 2024. Need more credits now? Upgrade for as little as $15/mo.
```

This might be caused by the usage of `arm.large` image for Linux and/or the recent addition of the Macos ARM64 build job.
At https://github.com/bioconda/bioconda-recipes/pull/50565 I am trying with a `arm.medium` image for Linux ARM64!

**Comment by martin-g** [comment]
Unfortunately the CircleCI check has disappeared for https://github.com/bioconda/bioconda-recipes/pull/50565 ...

**Comment by aliciaaevans** [comment]
I was not involved, but I believe there may be some sort of agreement with CircleCI so that Bioconda builds are not disabled even though we are over the credits. The jobs I see from that branch don't look like it's blocking arm.large from running, just a normal build error. https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes?branch=pull%2F50565

OSX ARM pushed us over the stated limit for the past few months, but it has not actually caused any problems besides that warning message. We can switch OSX ARM to GitHub Actions if necessary, but there are a few reasons that make it preferable to keep it on CircleCI (avoiding overlap of resources with bulk and bots, cleaner having two CI on PRs instead of three, etc.).

**Comment by martin-g** [comment]
The other day, when I opened this issue, the PR queue time was longer than normal. Now it seems to be back to normal again.
Closing this issue!
Thank you, @aliciaaevans !

**Comment by eunos-1128** [comment]
CircleCI checks seem to be stopped.

#50687
#50893

Is it related to credits?
