### ISSUE TITLE
How do I run travis tests in my fork?

### ISSUE THREAD

**Issue by jerowe** [bioconda/bioconda-recipes#5113]
@bioconda/core 

[Travis](https://travis-ci.org/jerowe/bioconda-recipes/jobs/250244881)

It tries to lint everything. I just did a pull from bioconda to 'my' master branch, still no joy.

Normally I like to test out PRs on my local docker image, then in my travis, then finally in bioconda.

**Comment by daler** [comment]
@jerowe after the linting updates, I now run local bioconda-utils build, then local simulate-travis.py, and then submit PR for testing on bioconda's travis-ci.

Here's the logic in question: https://github.com/bioconda/bioconda-recipes/blob/master/scripts/travis-run.sh#L27. What happens if you open a PR on your own fork (after updating your fork with upstream/master)?

**Comment by jerowe** [comment]
I don't know what happens if i open a PR on my own fork. Normally I just have a branch and let it run. Let's see!

Testing locally for me still works fine. If you're taking feature requests, it would be nice if it knew the bioconda utils would take into account that I have recipes built in the local file channel. (/opt/anaconda/linux-64? ). Sometimes when I have a large amount of recipes I build them in batches.

**Comment by daler** [comment]
@jerowe bioconda-utils should already consider your local channel, at least as determined from [`get_host_conda_bld`](https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/docker_utils.py#L179)

**Comment by jerowe** [comment]
It is probably just that I need to update my local build system and
bioconda utils. Thanks!

**Comment by jerowe** [comment]
I'll close this now. Thanks!
