### ISSUE TITLE
Build failure due to insufficient memory

### ISSUE THREAD

**Issue by joellembatchou** [bioconda/bioconda-recipes#51276]
This pertains to the PR #50468

The Azure pipeline check fails with message "We stopped hearing from agent Hosted Agent." and looking into the build log, there are [multiple warnings](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=71245&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572) pertaining to >96% of the memory being used.

Is there a way to increase the memory?

**Comment by aliciaaevans** [comment]
This does happen sometimes. There is not a way to increase memory for the Azure builds, but there are some workarounds like building it on the bulk branch which has 16GB RAM instead of 7, but that has to be done by a core member (I can do it but not sure if I'll have time in the next week or so). Are you able to build the recipe locally with success?

**Comment by aliciaaevans** [comment]
This PR was merged a while back. Also, we've switched over to GitHub Actions today, which should avoid this issue for other PRs.
