### ISSUE TITLE
promoting bioconda 

### ISSUE THREAD

**Issue by cokelaer** [bioconda/bioconda-recipes#5287]
Dear all, 

@johanneskoester 
@chapmanb 
@daler 
@bgruening 
@tomkinsc 

Note sure this is the best place to discuss this but following Brad's advice I open an issue to start a discussion on promoting bioconda even further thanks to a journal publication. I believe like all contributors to bioconda (I'm guessing ;-) ) that the core team has done an amazing job that helps some many of us developing faster and providing our tools to many end-users. Yet, we spend time on bioconda and for some of us this may be an issue in the future: indeed also what we do is valuable it may not be recognised for some of our funders or institutes. One way to be recognised is via publications (for those in research like me). So, I was wondering whether you discussed this possibility and if not whether you plan to do so. This could be also a valuable window for bioconda. Again, this is an amazing piece of work that has been put together and having a reference (although not required to make bioconda great)  could be used as a "reward" or motivation or justification for some of us. thanks for your feedbacks.

**Comment by chapmanb** [comment]
This is from a discussion at Codefest. +1 from me and I'm happy to contribute to writing, but we'd need someone to drive the publication.

**Comment by johanneskoester** [comment]
Yes, I already had plans to write a paper. Indeed, it feels right to do it now. I'll start drafting a manuscript (I'll invite you to the project) next week.

**Comment by tomkinsc** [comment]
Wonderful! Happy to help with it if I can!

**Comment by kyleabeauchamp** [comment]
I can help some with writing / editing.

**Comment by druvus** [comment]
Sounds like a good plan! Also happy to help.

**Comment by cokelaer** [comment]
okay cool, let me know if I can help.

**Comment by cbrueffer** [comment]
Great initiative, happy to help out.

**Comment by johanneskoester** [comment]
To give you an update: me and @daler have started some data analysis for the paper, see bioconda/bioconda-paper. I will post the URL to the draft as soon as I have made some more progress on it.

**Comment by jerowe** [comment]
I am a terrible, terrible writer, but I talk about how wonderful bioconda is all the time. ;-)

**Comment by HenningTimm** [comment]
Also happy to help with this.

I had an idea for an additional plot that I posted as an Issue in the paper repository.

**Comment by epruesse** [comment]
Also happy to help!

Bioconda pretty much solves a major issue in bioinformatics, and in particular an issue at the interface between bioinformatics and pure life-sciences researches: distribution.

Using Bioconda, installing tools becomes trivial for the "end user". At the same time the "developer" community can now build upon a much larger set of existing solutions without creating major installation/distribution hassles. Adding to that the conda intrinsic abilities to have old versions around indefinitely a good chunk of the "reproducibility" issue is addressed for free as well.

All in all, Bioconda has the potential increase the efficiency of progress in the field significantly, which should definitely justify a publication of some sort. 

Considering how likely the paper is to draw a lot of citations, something high ranking like a Brief Communication at NMeth could have good chances of being accepted. Did you guys inquire with them?

**Comment by johanneskoester** [comment]
Yes, Brief Communication in Nature Methods was what I wanted to aim for. I haven't yet contacted them. I'll need another week for the draft first (I have another deadline approaching fast).

**Comment by epruesse** [comment]
@johanneskoester You don't need a complete draft to do a presubmission inquiry. The form for those wants primarily title, abstract, authors and some info. Maybe upload one of the plots and have a rough title and abstract, that should be sufficient for them to decide whether it's something they want to publish. You could actually even contact (one of) the editors directly by email, just asking how they feel about a paper on Bioconda in their journal.

**Comment by dansondergaard** [comment]
Great idea!

I'm supervising a group of students who work for us contributing as many packages as possible to Bioconda (they're funded through ELIXIR) since Conda/Bioconda solves so many problems for our researchers. Maybe it's worth mentioning that there's on-going, funded work going into Bioconda to show how serious the research community is about this?

Anyway, I'd be happy to contribute something about our work to the paper if you guys find it useful :)

**Comment by bgruening** [comment]
@dansondergaard I have prepared already a small paragraph about bio.tools and the efforts in ELIXIR and de.NBI to support BioConda, just waiting for @johanneskoester to add this short paragraph. Would be great if you and Jon can then read over it.

**Comment by dansondergaard** [comment]
@bgruening I'll have a look at it, thanks!

**Comment by johanneskoester** [comment]
Dear all, I have finished the draft of the paper. I decided to finally try out [authorea](https://authorea.com) for writing it. [Here it is](https://www.authorea.com/189458/KlIqJYJOA5EPyUZjY9UG6g).
If you want to contribute, please sign up to authorea and post your username here, such that I can add you to the paper. @bioconda/core, please do that in any case. Even without contributing to the manuscript you should still be co-authors because of all your amazing work on the project.

Regarding the author list, I thought the following order would be reasonable:
@daler and @bgruening are co-first authors because of all their work on bioconda-utils and the packages, I am last author. In between we can order either by git commits or contributions to the paper itself. This is just a suggestion of course.

The target journal for now would be Nature Methods Brief Communications.

**Comment by jerowe** [comment]
@johanneskoester , this is awesome!

I think for contributing members you could give the url or give a supplementary table of all the contributing authors.

I would like to add a small paragraph on HPC and the suitability of conda/bioconda to managing multiple software stacks per lab, per project, and/or per user. You do state that conda is isolated and can manage multiple projects, but this is such an awesome feature that I feel it could have a few more sentences to do it justice.

**Comment by johanneskoester** [comment]
Yes, feel free to add such a paragraph! The supplementary table or a URL is a good idea, we should definitely do that. Let me know once you signed up, such that I can add you.

**Comment by jerowe** [comment]
I'm signed up under my work email, jdr400@nyu.edu, username jdr400. Name is still Jillian Rowe.

**Comment by cbrueffer** [comment]
Looks like a great start! My user number is 156882 (not sure where to find the username) with email christian.brueffer@med.lu.se, would be happy to contribute.

**Comment by chapmanb** [comment]
Brilliant thanks for writing this up Johannes. Happy to make some clean up edits directly as well if you can add me. I'm user 171999 signed up through GitHub.

**Comment by johanneskoester** [comment]
@cbrueffer I have added you, thanks! @chapmanb I have found your account already before I think. You should have access already.

**Comment by jerowe** [comment]
I fixed a few typos and made a few comments and a few comments on word choices. Feel free to throw those out. ;-) I also added a paragraph on HPC. I could expand on it if you want, but hopefully I made my point.

**Comment by tomkinsc** [comment]
I’d like to help. My user number is 172004.

**Comment by daler** [comment]
Nice Johannes! My ID is 172057

**Comment by rvalieris** [comment]
this is awesome @johanneskoester ! sorry I have not been active lately... but anyway my ID is 172044.

**Comment by epruesse** [comment]
@johanneskoester Great work, Johannes!

Nature commonly has long lists of authors, I've done as much as 99 (the MIMARKS paper), so there is room to include a lot of people. For MIMARKS we deliberately went that way, to create and demonstrate wide support for the standard. Similarly, a large list may make sense for Bioconda. The paper would double in purpose as a means for both promoting Bioconda and for honoring, motivating and binding the community members.

One idea for fairly pruning the 230 down to a manageable number might be to create an issue and pinging bioconda/all to provide a line or two each describing their individual contributions. The whole thing could then go into supplemental, further underscoring the scope of Bioconda. The need to see the ping, ask to be included and provide a justification should suffice to drop the list below 100. 

My authorea ID is 172069. I'd feel very honored to be included!

**Comment by bgruening** [comment]
@rvalieris @epruesse I added you both to the document, keep the comments coming.

**Comment by druvus** [comment]
I am happy to help. My ID is 172079.

**Comment by tomkinsc** [comment]
I made fairly sweeping revisions to most of the paper this morning, to spruce up grammar, etc. Authorea has a revision history, and the changes are visible there if there’s a desire to backtrack.

**Comment by epruesse** [comment]
Are you guys happy with Authorea? I find myself confused by the comments already littering the side in a not very helpful way. I also don't see a good way to suggest changes.

**Comment by daler** [comment]
@epruesse I'm a bit underwhelmed by it. There is a menu option to fork which seemed promising, but I was unable to find a way to push changes back to the document. And I find myself trying to aim my clicks precisely on overlapping text in comments to try and catch the right comment. I guess resolving some comments might help clean it up the latter issue. For suggesting changes, it seems that highlighting the relevant text, typing the replacement, and adding another comment to clutter the margin is the best method?

**Comment by daler** [comment]
@epruesse, looks like you can click on the "comment bubble" icon in the upper right, next to the "publish" button. That solves the comments problem for me by putting them in a clear list.

**Comment by johanneskoester** [comment]
Sorry about the glitches in authorea. It is a test for me as well. The editor can indeed be improved more.

**About the author list:**
To make that clear again, **everybody is welcome to join**! I am unsure how to organize that. The suggestion of @epruesse is maybe a good one. On the other hand, bioconda generates a lot of email notifications and people might miss another thread about joining. Maybe it is more fair to simply include everybody in the team?

**Comment by cbrueffer** [comment]
I think in the end something like a GH issue may be practical to ensure that every author has read and approved the final manuscript.

**Comment by johanneskoester** [comment]
@cbrueffer yes, we also need full name and affiliation for every co-author.

**Comment by kyleabeauchamp** [comment]
My ID is 172340

**Comment by bgruening** [comment]
I added you @kyleabeauchamp a few minutes ago.

**Comment by notestaff** [comment]
My ID is 172422

**Comment by johanneskoester** [comment]
@notestaff I think I need your email address or username in order to add you to the paper.

**Comment by notestaff** [comment]
@johanneskoester I'm ilya_shl@alum.mit.edu

**Comment by johanneskoester** [comment]
Ok, added you.

**Comment by johanneskoester** [comment]
Ok, the issue for the affiliations is open: #6323.

**Comment by johanneskoester** [comment]
I will try to submit soon. Please avoid edits to the manuscript from now on.

**Comment by johanneskoester** [comment]
I just submitted the paper to nmeth. Thanks guys for your tremendous help! It is really an honor to have such amazing and dedicated team mates. If this goes through, we should find a way to meet and have a party :-)!

**Comment by bgruening** [comment]
I propose a hackathon-party in europe early next year! :)
Thanks @johanneskoester for all your work on the paper and the final submission!

**Comment by cbrueffer** [comment]
Indeed, thanks for making this project and and the paper so open!

**Comment by johanneskoester** [comment]
Dear authors,
Nature Methods has agreed to consider the paper, if it is shortened to correspondence format. I have done this now, and moved several paragraphs into the supplement. The text itself has barely changed. Hence, in order to allow rapid resubmission, I think we should another round of reviews or edits from everyone. If there is a pressing issue, please let me know via this thread during the rest of the day.

* [Main article](https://www.authorea.com/217614/1C5uqdwKI_Rui60-qXMuwg)
* [Supplement](https://www.authorea.com/217734/tAyK6IfbF5DL4VC3Zkvpyw)

**Comment by chapmanb** [comment]
Johannes -- thanks for the work reformatting it and driving it through. That is an amazing amount of info to pack into a short amount of space. Fingers crossed on the submission.

**Comment by kyleabeauchamp** [comment]
LGTM!

**Comment by johanneskoester** [comment]
Thanks guys! I have just resubmitted it.

**Comment by johanneskoester** [comment]
Dear all,
I just received the reviews for the paper. They are quite positive and we should be able to address them. I will keep you posted on the process.

Happy new year!

**Comment by cbrueffer** [comment]
That's great news Johannes, thanks for the update! Let us know if we can help with anything.

**Comment by chapmanb** [comment]
Brilliant, nice work Johannes. Fingers crossed for a clean re-submission.

**Comment by cokelaer** [comment]
Awesome news to start the new year ! thanks for the hard work.

**Comment by johanneskoester** [comment]
Reviews are back. We are basically accepted! Only one concern remained, which I have addressed here: https://www.overleaf.com/read/chxnxkkpczjc
Let me know if you have any comments on the response, otherwise I will resubmit later today.

**Comment by chapmanb** [comment]
Johannes -- amazing news, thanks for finalizing this. Looking forward to seeing it out.

**Comment by epruesse** [comment]
@johanneskoester Are we permitted to peek at the reviewer comments? Since it's nearly through, it really is more of a curiosity. I am curios though :*)

W.r.t. your reply - you kind of mix your roles as Snakemake author and Bioconda author there.

In general, depending on the original comment, it may be worthwhile to point out that:

Reproducibility as provided by Bioconda is inherently limited to reproducing binary packages. Compensating for, or even just mitigating, the effects of non-determinism such as intentionally introduced by modern operating systems to improve system security, effects caused by differences in CPU micro architecture or even just by IO latency variations or the amount of available memory, is out of scope. While there are tools attempting to provide this level of reproduction, the computational cost is not justifiable in general scientific environments. 

Many of the tools distributed by Bioconda support multiple operating systems and architectures by implementing alternative code paths, both to  cater to idiosyncrasies and to exploit unique features. While freezing the packages and their versions allows reproducing them at a later time, switching architectures will yield different binaries which will behave differently. While the differences are usually not significant, optimal reproduction of a workflow is therefore achieved by first reproducing the OS and architecture layers using VM technology. `docker-machine` does this on macOS by default using VirtualBox to create a Linux environment. It should be noted that this ordinarily does not reproduce CPU feature dependent optimizations in tools (e.g. AVX CPU feature support).

(Uh, maybe shorter than that, lest someone want an additional discussion of reproducibility in general, which is completely out of scope. Assume a tool was dependent on Meltdown behavior... ;)

**Comment by epruesse** [comment]
Of topic, but thinking on this, reproducibility probably means that we should use `track_features` to compile alternative binaries with CPU feature support (like say SSE4.2 or AVX2).

**Comment by kyleabeauchamp** [comment]
I have currently been exploring builds with more aggressive CPU features, optimizations, and compilers---and I've found there is some performance to be had (~10%), at least in the case of BWA.

**Comment by kyleabeauchamp** [comment]
Definitely will be good to explore once we get the GCC 7X series compilers and CB3 support.

**Comment by epruesse** [comment]
@kyleabeauchamp It's most significant for tools written in C/C++ with the automatic vectorizer in GCC specifically in mind. If you keep your loops clean, GCC will generate SIMD code on its own, but only using newer versions and adequate flags. In those cases, order(s) of magnitude difference are possible. See e.g. `dada2`. This digresses here though.

**Comment by johanneskoester** [comment]
@epruesse the only comment is directly above my response. There were no other reviewer comments at this stage. Your discussion is valid, but this all happened in the previous iteration and those arguments are in the revised version of the manuscript. At this stage, the reviewer is already happy and just had a final misunderstanding about what the workflow archive supports.

**Comment by johanneskoester** [comment]
@epruesse yes, I do indeed mix the roles here. This is because I was forced to address these more Snakemake-ish questions of that particular reviewer (also in the previous release). The paper workflow was never intended as an example or use case, but it was interpreted like that. So, we have to deal with it ;-). But that is fine, it only shows how dedicated the reviewer is, and it also made the paper and the analysis better and more reproducible.

**Comment by epruesse** [comment]
@johanneskoester I figured. Doesn't matter - it just needs to be out there. It's a topic for the next paper ;*)

**Comment by bgruening** [comment]
@epruesse https://www.biorxiv.org/content/early/2017/10/11/200683

**Comment by bgruening** [comment]
Thanks @johanneskoester!

**Comment by epruesse** [comment]
@bgruening Thanks! Thought it was worth a separate paper! :)
@johanneskoester Thanks for getting the paper done!

**Comment by jerowe** [comment]
This is amazing! Thanks and congrats!

**Comment by cokelaer** [comment]
Brilliant, thanks a lot.

**Comment by johanneskoester** [comment]
I have just uploaded the final version of the manuscript, including all the paperwork :-). Editing might still take some time though, hopefully not weeks. Thanks to all of you for your help in getting this done!

**Comment by tomkinsc** [comment]
Thank you for leading the effort, @johanneskoester! Hopefully the manuscript will sail through to publication.

**Comment by johanneskoester** [comment]
I am happy to say that the paper will be in the July issue of Nature Methods!

**Comment by bgruening** [comment]
The paper is out:  https://www.nature.com/articles/s41592-018-0046-7

**Comment by PertuyF** [comment]
Congrats!
Do you have a timing for the open access release?

**Comment by johanneskoester** [comment]
I think it was 6 months. In the meantime, here is the public view only link: https://rdcu.be/2kbI
