### ISSUE TITLE
suggested change to phyloseq instalation instructions

### ISSUE THREAD

**Issue by ohnoplus** [bioconda/bioconda-recipes#5491]
The instructions on this page did not work for me

https://bioconda.github.io/recipes/bioconductor-phyloseq/README.html

I found that rather than the following suggested command
`conda install bioconductor-phyloseq`

The following command actually seemed to install phyloseq.
`conda install -c bioconda bioconductor-phyloseq`

 If this isn't super specific to me, it would be nice if somebody would update the instructions. If this is the wrong place for me to request this, I'd appreciate any advice about where I should take this request

**Comment by daler** [comment]
@ohnoplus this is definitely the place to bring up these kinds of issues. However on that page, just before `conda install bioconductor-phyloseq` it says:

> With an activated Bioconda channel (see [2. Set up channels](https://bioconda.github.io/index.html#set-up-channels)), install with:

Follow that link to set up the channels, which is important to do because it includes `conda-forge` as well as `bioconda` and puts the channels in the correct order so that everything in bioconda will install easily.

**Comment by bgruening** [comment]
@ohnoplus hope that @daler comments help. Will close this now. Please feel free to reopen!
