### ISSUE TITLE
Issues with xxd and clang for building a MMseqs2 recipe

### ISSUE THREAD

**Issue by martin-steinegger** [bioconda/bioconda-recipes#6588]
We tried to build a bioconda package for MMseqs2 (https://github.com/soedinglab/mmseqs2), but we running into some issues:
1.) Is there a way to enforce the GNU g++ compiler for MacOS? ? The system clang of MacOS does not support OpenMP.
2.) We use`xxd` during build, but there seems to be no package available for it (usually vim-common on linux distributions). Do we need to build our own xxd package (or vim-common) package? The is no cross platform vim package available currently.
3.) If we cannot solve these issues easily. Can we ship a conda recipe that downloads static MMseqs2 builds from our server (similar to the blast packages).
4.) We require at least SSE4.1 CPU support for our software. AVX2 (a compile time choice) support is also implemented. What is the best way for users to always get the best possible performance, when they install MMseqs2 through conda?

**Comment by milot-mirdita** [comment]
We just resolved the second issue in MMseqs2 by using the [xxdi.pl](https://github.com/gregkh/xxdi) if xxd is not available. Perl seems to be available as a conda build dependency.

We would still require guidance for the other issues.

**Comment by jmeppley** [comment]
Have you made any progress with a mmseqs2 conda package?

**Comment by martin-steinegger** [comment]
@jmeppley Unfortunately, we did not. The issues are still not resolved. We are still waiting to get support from the bioconda community.

**Comment by daler** [comment]
@martin-steinegger:

(sorry it took so long for someone to respond, this apparently slipped through the cracks)

1. Does requiring `llvm` work? Or `gcc`? @bioconda/osx can help here. You could also grep for OpenMP in the recipes to get ideas on what other folks are doing for similar situations.
2. In general, yes a new package for xxd would be required; since this is non-biology specific it should be submitted to the conda-forge channel.
3. We try to use this only in worst-case scenarios so is not preferred (we are in fact compiling blast on each platform!)
4. @kyleabeauchamp has been looking into similar issues with `bwa`, but IIRC the verdict at this point is that there is no good way a) to build such packages on our infrastructure or b) for conda to install optimized builds. Maybe Kyle could give some more insight.

If xxdi.pl mentioned by @milot-mirdita is sufficient, then perhaps getting OpenMP working with MacOS would be enough to get a (non-optimized) package into bioconda.

@bioconda/core anything else to add?

**Comment by kyleabeauchamp** [comment]
Regarding (4), I think the two remaining to-do items are: 

(A)  Figure out a way to propagate (through the bioconda architecture) arbitrary "feature flags" for conda packages that have been compiled with extra optimizations
(B)  Use the latest compilers that are now available in conda build 3

**Comment by martin-steinegger** [comment]
Thanks for your help @daler  and @kyleabeauchamp. I tried to build the recipe but the linter complains about our version string (whose format is already a compromise and will not change). What can we do to still build the package?

```
Filtering 1 of 1 (100.0%) recipes/mmseqs2
Error: bad character '-' in package/version: 2-23394
Error: Exited with code 1
Step failed
Task failed
```

Our build script and yaml looks like this:
meta.yaml: https://gist.github.com/martin-steinegger/e0a7332f727297f6cd6f91b4c20b890e
build.sh: https://gist.github.com/martin-steinegger/f36ad869462c984542c5806c9ea0beee

**Comment by peterjc** [comment]
I think you'll have to adapt the version number for the point of view of packaging, e.g. would 2.23394 work for you?

**Comment by martin-steinegger** [comment]
I found a hack that worked for me. Thanks @peterjc.
  
    version: {{ version|replace("-", ".")  }}

I have a working mmseqs2 recipe now but I do not have the permission to push it. How can I push it?

**Comment by mdehollander** [comment]
You can create a pull request. See the instructions on how to contribute for more information: https://bioconda.github.io/contribute-a-recipe.html

Nice you made a conda pakcage for mmseqs2. We will give it a try when it is merged!

**Comment by jmeppley** [comment]
Thanks @martin-steinegger for making the package, and for eveyone else chipping in. I'm trying it out now.
