### ISSUE TITLE
NameError: global name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by ademcan** [bioconda/bioconda-recipes#6755]
Hello, I am trying to build a new recipe for a CRAN R package with the following command "./simulate-travis.py --packages r-rcolorbrewer". Everything seems to be working fine, I even have the "successfully built recipe" message. However, the command ends up with a FileNotFoundError error and I don't get any more information. I would be happy if someone could help me with that.
Thanks a lot.

15:27:39 BIOCONDA INFO BUILD SUMMARY: successfully built 1 of 1 recipes
+ set +x
Traceback (most recent call last):
  File "./simulate-travis.py", line 411, in <module>
    _docker_machine_run_travis(env)
  File "./simulate-travis.py", line 301, in _docker_machine_run_travis
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

**Comment by daler** [comment]
Based on that error, it looks like you are on macOS and but do not have docker installed. You can either install docker so that you can test recipes on Linux within the docker container, or (much easier!) use the `--disable-docker` argument to disable testing with docker.

However the error itself is complaining that FileNotFoundError is not defined, but it is a [built-in exception](https://docs.python.org/3/library/exceptions.html#os-exceptions). There should have been a message like [this](https://github.com/bioconda/bioconda-recipes/blob/master/simulate-travis.py#L302). I wonder if there is a Python version issue happening here . . . did you run `.simulate-traivs.py --bootstrap` before running your tests?

**Comment by ademcan** [comment]
Yes, I am on macOS, but Docker is installed. I had to start it as well from the command line with `docker-machine start`. I already ran `.simulate-traivs.py --bootstrap`. 
In the end, it worked when I used the `--disable-docker` parameter, thanks a lot :)
