### ISSUE TITLE
Travis error with OS X recipes for R; dyld: Library not loaded: @rpath/libintl.9.dylib

### ISSUE THREAD

**Issue by cbrueffer** [bioconda/bioconda-recipes#6775]
For some bioconductor R packages I'm adding (e.g., #6746, #6753 ) I see build failures in the same vein as described in conda-forge/staged-recipes#3452. There seems to be a gettext incompatibility somewhere.

**Comment by cbrueffer** [comment]
Another one, #6860

**Comment by cbrueffer** [comment]
The answer to this seems to be conda-forge/r-nloptr-feedstock#4

**Comment by mbargull** [comment]
Some of those might very well be caused by a bug in Conda: https://github.com/conda/conda/issues/6269.
Take `bioconductor-flowploidy` in #6746 for example:
`bioconductor-flowploidy` depends on `r-nloptr` via `r-car`.
The build failure is due to an import error for `r-nloptr` as that package came from `defaults` but not `conda-forge` and there are some incompatibilities between those channels: https://github.com/conda-forge/conda-forge.github.io/issues/434.
But an up to date version of `r-nloptr` is actually available on `conda-forge`! But then comes the bug from https://github.com/conda/conda/issues/6269 into play: to minimize the needed feature count Conda tries to avoid the `blas_openblas` and `debug` feature. If we explicitly request packages for which some builds require those features, Conda doesn't try to avoid them and we get `r-nloptr` from `conda-forge`.
You can see the difference if you run
```
conda create -n x --dry-run -c bioconda -c conda-forge -c defaults r-car r-base python blas=1.1
```
instead of simply
```
conda create -n x --dry-run -c bioconda -c conda-forge -c defaults r-car r-base
```

So, that might be the cause of (some?) of those build issues. But sadly I currently can't offer a solution or workaround.

**Comment by cbrueffer** [comment]
Yeah, that's roughly the same reasoning described in conda-forge/r-nloptr-feedstock#4

**Comment by mbargull** [comment]
Quick update:
The packaging issue of R packages in `defaults` has been resolved: https://github.com/conda-forge/r-bradleyterry2-feedstock/pull/1#issuecomment-347006104.
I restarted the build for https://github.com/bioconda/bioconda-recipes/pull/6792 and in the meantime https://github.com/bioconda/bioconda-recipes/pull/6792 and https://github.com/bioconda/bioconda-recipes/pull/6860 were restarted as well.
But sadly, the issue I pointed at is still blocking these.

**Comment by mbargull** [comment]
Hi @cbrueffer, I noticed you tried to restart your builds again. Bioconda hasn't updated to `conda 4.3.33`, [yet](https://github.com/bioconda/bioconda-utils/pull/259) (the long macOS backlog on Travis CI held things back for a couple of days). Give it another try once we did!

**Comment by cbrueffer** [comment]
Thanks for the heads-up! Some packages that failed before actually already build (e.g. bioconductor-rnaither).

**Comment by mbargull** [comment]
Yeah, I think (dependency and version) updates to some packages that happened in the meantime could have "persuaded" the `conda`'s solver to pick the wanted `conda-forge` variants. Maybe some of those updates may have just went online in the last couple of days -- those intermediate changes got me confused just this morning at https://github.com/conda-forge/r-bradleyterry2-feedstock/pull/1#issuecomment-361052361 😆

**Comment by cbrueffer** [comment]
This appears to be working OK now, so close the PR.
