### ISSUE TITLE
Quast 4.6.1 incomplete package

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-recipes#7349]
Since 4.6.1, the `quast` package no longer includes the BLAST database built from SILVA and does not include an install script or post_inst hook to complete the package after installation.

This leads to problems e.g. with Snakemake workflows using conda to implicitly provide environments. Firstly, the files downloaded by quast on the fly end up in the local environment, not in the `$CONDA_ENV/pkgs/quast...` folder, so they are downloaded for each environment again and again (i.e. for each Snakemake working directory). If a Snakemake workflow is run with parallelism, quast will also terminate with a bunch of exceptions resulting from a race condition downloading and building that reference.

Could we have a `quast_download_databases` style script in the package? Or even a post_inst hook? Or maybe just have that blast database distributed with the package, or in a companion package `quast-dbs` (as it's life cycle is probably independent from quast itself).

**Comment by epruesse** [comment]
ping @alexeigurevich 

See also #7008

**Comment by alexeigurevich** [comment]
Hi!
Could you add execution of `metaquast --test-no-ref` in the appropriate place (post_inst/script/etc?). This would download and configure BLAST/SILVA related stuff. 
Note that the maintainers asked to remove this part from the Quast default package since SILVA is really huge (and relatively rarely needed for the majority of users).

**Comment by mbargull** [comment]
@epruesse, if this is a pressing issue for you and you don't want to wait until we decided how to approach this problem for the `quast` package, I believe, you could (as a temporary measure) run
```bash
python -c 'from quast_libs.search_references_meta import download_blastdb; download_blastdb()'
```
inside the environment you installed `quast 4.6.1` into. @alexeigurevich, correct me if I'm wrong and that command doesn't suffice to get the database ready.

If you have a workflow that frequently creates new environments and you are concerned about the repetitive downloads, a `quast_download_databases` or `post-link.sh` script won't get you far as they will download the database for every `quast` install (i.e., a `post-install.sh` can't make use of Conda's cache). So for this scenario I only see the two possibilities to avoid multiple downloads:
1. put the database (semi-)manually in place,
2. create a `quast-dbs` package.

Regarding 1., this could be done
 * semi-automatic by redirecting the download of http://www.arb-silva.de/fileadmin/silva_databases/release_123/Exports/SILVA_123_SSURef_Nr99_tax_silva.fasta.gz by a local proxy and using the command I gave above.
 * manually by letting `quast` download it once and then copying the file manually every time.

Regarding 2., we'd may need a dependency between `quast-dbs` and `quast` since when the location for the database would be changed in Quast, the database package needed to be changed accordingly.
As for whether its desirable to have database packages: There are some storage limits on `anaconda.org` which Anaconda graciously and repeatedly upped for `bioconda`. But it's be still preferable to keep the package sizes small. As for `quast`, that package would actually be really small if it wouldn't bundle its dependencies. But if you include the database the package grows to around 150 MiB and if we were to add Python 3 packages, we'd triple that storage need for each build...

**Comment by mbargull** [comment]
@alexeigurevich: If we were to include scripts to download the excluded dependencies:
1. What do you think they should do? Just the opposite of https://github.com/bioconda/bioconda-recipes/blob/master/recipes/quast/pre-unlink.sh ?
2. Should that be separate scripts (one for SIVLA, one for Manta, and another one for Manta) or just one that installs all of them?
3. Should that be done in a `post-install.sh` so that they are downloaded/installed for every `quast` install or rather not, given your comment "relatively rarely needed for the majority of users"?

**Comment by mbargull** [comment]
Note to myself: Maybe we should add a `post-install.sh` in any case which prints out that those dependencies are not included and how to install them.

**Comment by alexeigurevich** [comment]
Hi @mbargull and @epruesse !

> 1. What do you think they should do? Just the opposite of https://github.com/bioconda/bioconda-recipes/blob/master/recipes/quast/pre-unlink.sh ?

Yes, I think this is what is needed -- `download_blastdb` and `download_manta`. Also you may need `download_blast_binaries` or ask conda to install `makeblastdb`, `blastn`,  and `tblastn` into PATH.

> 2. Should that be separate scripts (one for SIVLA, one for Manta, and another one for Manta) or just one that installs all of them?

I think both approaches make sense. When you want to use SILVA you may expect matching against inexact reference genomes (found by search in SILVA) and thus structural variants detection using Manta would be helpful (i.e. both tools are needed). At the same time, some users may want to use Manta but do not need SILVA at all (i.e. only one tool is needed). I personally think that separate scripts are better, taking into account that we will submit Manta by another tool in the next Quast release while SILVA remains in place.

> 3. Should that be done in a post-install.sh so that they are downloaded/installed for every quast install or rather not, given your comment "relatively rarely needed for the majority of users"?

No, I think rather not. If we want them for every quast install we should rather switch back to `install_full` in the main script but I think we do not want this.

**Comment by epruesse** [comment]
> What do you think they should do?

Well... WE need to figure out a good way to deal with the reference databases. Until then:

 - Allow telling `*quast` where to look for its reference databases. Whether that's a parameter or an environment variable doesn't matter, as long as it doesn't require monkey patching. Perhaps even have a "search path", definitely have a single place the default path is configured so that it can be patched by package maintainers (FHS calls for `share/quast` rather than `lib/python-X.Y/site-packages/quast`).
 - Separate the download-and-db-prep stage out into a script that can be called explicitly, e.g. 
   ```
   quast_download {--silva|--manta|--all} [--remote|--file <path-to-tgz>] \
                  [--dbdir <path-to-dbs]
   ```

We could then have one or more meta-packages, e.g. `quast-dbs` requiring `quast-db-silva` and `quast-db-manta`, which in turn might even require `manta-db` and `silva-db`. The `*-db` packages could then take care of downloading the respective reference DB. The `quast-db-*` packages take care of doing the quast specific modifications. Depending on licensing and storage etc. we might eventually do part of the downloading / prep on the CI.

**Comment by mbargull** [comment]
Hi @epruesse,

> WE need to figure out a good way 

Oh, with "they should do" I meant to say "those [the scripts] should do" -- sorry for being imprecise and causing confusion there!

> Allow telling *quast where to look for its reference databases

That sound like a (very good and reasonable) feature request for QUAST itself -- you might want to create an issue over at their repo for this.

> We could then have one or more meta-packages, e.g. `quast-dbs` requiring `quast-db-silva` and `quast-db-manta`

We haven't done that, but @alexeigurevich just updated the `quast` recipe to `4.6.3` in #7546 which now includes two scripts `quast-download-manta` and `quast-download-blastdb` which will download and install the omitted dependencies.

**Comment by epruesse** [comment]
> Oh, with "they should do" I meant to say "those [the scripts] should do" -- sorry for being imprecise and causing confusion there!

:-D

Sorry, I had wrongly assumed more involvement upstream. Can't be sure around here ;-)

Anyway, I think having `quast-download-xxx` scripts fixes the problem well enough.

**Comment by mbargull** [comment]
Great, glad to hear that!
