### ISSUE TITLE
Possible to remove old R packages from channel?

### ISSUE THREAD

**Issue by garrettjstevens** [bioconda/bioconda-recipes#8042]
Hi all, thanks for all the work you do on Bioconda. It's really a great tool to have.

I know that last year a bunch of R packages were migrated to conda-forge (https://github.com/bioconda/bioconda-recipes/issues/5582). However, some old packages still seem to be in the Bioconda channel. As an example, the package `r-caroline` was migrated, but if you run `conda info r-caroline`, you can see there are still old versions of it in the Bioconda channel (see output below). Since Bioconda is my highest priority channel, it still tries to grab the old version from Bioconda instead of the new version from conda-forge.

Is it possible to remove those packages from the Bioconda channel? I understand they may need to stay for legacy/backwards compatibility purposes, but it seems like it would be nice if they could be removed. First of all, it would be nice to get the latest version of those packages without having to change my channel priority. Second, I just recently started having problems where my conda env creations will hang indefinitely (à la https://github.com/conda/conda/issues/5536). I've already removed the R channel like that thread suggests, but I think the same conflicts that were happening between the R channel and conda-forge are now happening between conda-forge and Bioconda. I'm working around this for now by adding `--no-channel-priority` to my env creation, but that really only works for small mostly-R envs.

I'm also not sure if there's an easy way to tell which packages are affected. The ones I have noticed are:
`r-caroline`
`r-ggrepel`
`r-optparse`
but I'm sure there are more. I can try to create a more comprehensive list if it's helpful.

Thanks for your time.

Output of `conda info r-caroline`:
```
r-caroline 0.7.6 r3.3.2_0
-------------------------
file name   : r-caroline-0.7.6-r3.3.2_0.tar.bz2
name        : r-caroline
version     : 0.7.6
build string: r3.3.2_0
build number: 0
channel     : conda-forge
size        : 116 KB
arch        : x86_64
has_prefix  : False
license     : Artistic-2.0
license_family: OTHER
md5         : 14253cfa1813ad9c7fa6c5d30ed4a054
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/r-caroline-0.7.6-r3.3.2_0.tar.bz2
dependencies:
    r-base 3.3.2*

r-caroline 0.7.6 r3.4.1_0
-------------------------
file name   : r-caroline-0.7.6-r3.4.1_0.tar.bz2
name        : r-caroline
version     : 0.7.6
build string: r3.4.1_0
build number: 0
channel     : conda-forge
size        : 116 KB
arch        : x86_64
has_prefix  : False
license     : Artistic-2.0
license_family: OTHER
md5         : 199c2c3c59dfdf1ab87fbf74431845e7
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/r-caroline-0.7.6-r3.4.1_0.tar.bz2
dependencies:
    r-base 3.4.1*

r-caroline 0.7.6 r3.3.1_0
-------------------------
file name   : r-caroline-0.7.6-r3.3.1_0.tar.bz2
name        : r-caroline
version     : 0.7.6
build string: r3.3.1_0
build number: 0
channel     : bioconda
size        : 111 KB
arch        : x86_64
has_prefix  : False
license     : Artistic-2.0
license_family: Proprietary
md5         : 4f64396f7282819d4df741221cc93429
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/bioconda/linux-64/r-caroline-0.7.6-r3.3.1_0.tar.bz2

dependencies:
    r-base 3.3.1*

r-caroline 0.7.6 r3.3.2_0
-------------------------
file name   : r-caroline-0.7.6-r3.3.2_0.tar.bz2
name        : r-caroline
version     : 0.7.6
build string: r3.3.2_0
build number: 0
channel     : bioconda
size        : 114 KB
arch        : x86_64
has_prefix  : False
license     : Artistic-2.0
license_family: Proprietary
md5         : afae7500945de6f001da2a50720c5b68
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/bioconda/linux-64/r-caroline-0.7.6-r3.3.2_0.tar.bz2
dependencies:
    r-base 3.3.2*
```

**Comment by bgruening** [comment]
@garrett-stevens could you not pin your r-packages to a newer version in your environment file? That should solve it I think.

**Comment by garrett-stevens** [comment]
Hmm, for some of them I could do `conda install "r-package>=x.x"` and that should work, but for some of them the most recent version of the tool is in both channels. I might try pinning the packages to a specific channel like this:
```
$ conda config --system --add pinned_packages conda-forge::r-package
```
That should work, as long as I can track down all the packages that need to be pinned in order for the conda installation to stop hanging. I was just thinking that if the old packages got removed from the Bioconda channel, it would prevent others in the future from running into the same problem.

**Comment by vinjana** [comment]
I am strongly against removing old packages from bioconda, in particular as a dirty fix of conda bugs, like the described infinite waiting. Removing old packages is a threat to reproducibility.

First, environments depending on old versions break and are unusable until s.b. took the time to update them (just from a technical perspective). We have now two workflow environments that already refuse to build from existing YAML dumps, because r-getopt is not available for 3.3.1 and because suddenly additional packages are needed (Did someone change the build descriptions? I didn't go into the details yet). 

Second , -- and worse -- who is guaranteeing reproducibility of the underlying analyses? With a switch from R 3.3.1 to 3.3.2 I would not worry too much, but I have not yet checked, whether all bioinformatic packages are still available with R 3.3.2. 

We planned to use [bio]conda to ensure a reproducible environment in a scientific production system for the analysis of thousands of human genomes. Now I have doubts that this is a good idea. Also, when suggesting bioconda to bioinformatic users I can now only tone down the enthusiasm with a remark on lack of long term guarantees.

Or did we understand this incorrectly, that reproducibility of the environments is one of the major aims of the whole conda system and bioconda? At least that is what the [docs](https://bioconda.github.io/faqs.html#what-s-the-lifecycle-of-a-bioconda-package) say

> Once uploaded to anaconda.org, it is our intention to never delete any old packages. Even if a recipe in the bioconda repo is updated to a new version, the old version will remain on anaconda.org.

Could be that my dubious experiences with our workflows have other causes (as I said, just started investigating). @bgruening I'd be happy to hear your comments on current guarantees of old package availability -- in particular with respect to the mentioned r-getopt and similar packages.

**Comment by garrett-stevens** [comment]
I agree that removing packages could cause some problems, so maybe there is another way to solve my original problem? Basically the issue I'm still having is:
- Bioconda requires a certain channel priority to run (bioconda then conda-forge then defaults)
- Some packages have moved from bioconda to conda-forge, but since those packages have old versions in bioconda, an environment configured with the proper bioconda channel priority will grab the old bioconda version instead of the new conda-forge version

For now I'm just checking packages manually and pinning them or installing them with `--no-channel-priority` as needed, but it would be nice to have a general solution to this that doesn't involved manually checking packages.

**Comment by bgruening** [comment]
@garrettjstevens we highly recommend to put conda-forge as number one priority channel.
See here: https://bioconda.github.io/user/install.html#set-up-channels
