### ISSUE TITLE
Software version not updated in Available Packages section 

### ISSUE THREAD

**Issue by nupurgunwant** [bioconda/bioconda-recipes#9441]
I updated a software last week, and the PR was merged #9269 . 
However, I couldn't find the changes here: https://bioconda.github.io/recipes.html
I could however see them on anaconda : https://anaconda.org/bioconda/intermine
Am I missing something, or is the 'Available Packages' section not maintained anymore?

**Comment by daler** [comment]
@nupurgunwant the documentation is compiled each time a branch is pushed to the master branch of bioconda-utils. We've been busy on other branches, so that hasn't happened in a while. 

We should instead be building the docs nightly so it stays updated. I just opened https://github.com/bioconda/bioconda-utils/issues/309 to track this issue.
