### ISSUE TITLE
Erroneous black listing of packages due to errors updating meta.yml

### ISSUE THREAD

**Issue by molpopgen** [bioconda/bioconda-recipes#9901]
A few of the recipes that I maintain are blacklisted via recent commits by @bgruening and others.  These are due to commits like [this](https://github.com/bioconda/bioconda-recipes/commit/31f2bc37fa14a7a1b51451383bcb39909f50f741) which set the compiler to 'c' for C++ packages.

Somehow, this blacklisting didn't happen to all packages, though.  Yesterday, I updated the libsequence recipe.

However, fwdpp and fwdpy11 are blacklisted due to "compiler error", which is not the case.

It looks like this happened via a few big "bulk" PRs, but the recipes affected should be flagged and gone through manually in order to fix this?  Most of these packages would be documented as C++ on their home pages, etc.

**Comment by bgruening** [comment]
@molpopgen I'm working since a month or so now on the cb3 migration. For this we needed to rewrite every recipe and rebuild them.

The C/C++ situation is a little bit tricky as previously we did not distinguish them. Today we do, so I ported everything to the more conservative one and fix them gradually. I can not look at every pkg why it is failing. So if I do think I now a solution for a failing recipe I fix it, and I did this now for many hundreds of pkgs, but if the error message is cryptic or it looks like it needs more work I blacklist them and many other people like @dpryan79 trying to fix them.
I try to add a sentence and try to group the failing recipes to make contributions easier, for example there are a lot of failing pkgs because they can not find zlib and so on. So any help is welcome. Just uncomment the pkg from the blacklist, see what the error is and fix it :)

This will hopefully be over soon, I don't want to spend an other month of my life with this. Our recipes should be in a way better shape as they are currently.
