### ISSUE TITLE
recipes using gcc are built using container's gcc?

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#9920]
@bioconda/core I was doing some troubleshooting and I think as currently configured we're using the container's gcc, not conda gcc, when building recipes. Is that intended? I'm admittedly out of the loop recently, particularly when it comes to cb3 compilers.

The script below removes `gcc` from the container (it actually removes devtoolset2) and then tries building bowtie2. It fails because it can't find g++ -- even though the recipe specifies `build: {{ compiler('cxx') }}`. I would have though that the new `build:` section installs g++. In fact, the log does say 
```
The following NEW packages will be INSTALLED:
              
    toolchain:              2.1.6-0 conda-forge
    toolchain_cxx_linux-64: 2.1.6-0 conda-forge
```
But apparently that's not enough. I tried to set up this environment as closely as I could to the actual build environment -- am I setting it up incorrectly?

```bash
#!/bin/bash

docker run --rm -it bioconda/bioconda-utils-build-env:cb3-migration /bin/bash -c '

# get rid of local gcc
yum remove gcc -y

# Install bioconda-utils branch cb3-migration
git clone https://github.com/bioconda/bioconda-utils.git
(
  cd bioconda-utils/
  git checkout cb3-migration
  python setup.py develop
)

# Clone bioconda-recipes
git clone https://github.com/bioconda/bioconda-recipes
cd bioconda-recipes

# to avoid building older versions
rm -rf recipes/bowtie2/2.2*

# error: "/bin/sh: g++: command not found"
bioconda-utils build recipes/ config.yml --packages bowtie2 --force
'
```

**Comment by bgruening** [comment]
@daler are you talking about gcc or 
```
  build:
    - {{ compiler('cxx') }}
```

@mbargull is working on removing GCC from the conda-forge base image currently.

**Comment by daler** [comment]
@bgruening sorry in my mind gcc and g++ are conflated. 

I'm saying that when devtoolset2 (which includes gcc and g++) are removed from the container, I would expect this:

```
  build:
    - {{ compiler('cxx') }}
```

to install a C++ compiler to be used by conda when building the recipe. The above script shows that this is not the case.

This implies that all compiled recipes will no longer compile if @mbargull removes gcc and g++ from the container!

**Comment by mbargull** [comment]
It's a tad confusing, I know...
So here is the thing broken down:
1. `conda-build 3` introduced the `{{ compiler(...) }}` Jinja 2 functions.
  - For its default configuration, `conda-build 3` would evaluate `{{ compiler('c') }}` to `gcc_linux-64` on Linux.
  - `gcc_linux-64` is the GCC 7.2 package (technically the GCC is in a dependency package, but let's not bikeshed :wink:) on the `defaults` channel that has activation scripts which set `CC`, `CFLAGS`, ..., and it used`run_exports` and ships glibc in a sysroot and all that glory.
2. `conda-forge` does not yet use the compiler packages from `defaults` and thus no GCC 7.2
  * `conda-forge-pinning` provides a `conda_build_config.yaml` that conda-forge (as well as Bioconda) uses which overrides the default behavior and instead of `gcc_linux-64` uses `toolchain_c_linux-64`.
  * `toolchain` is the "traditional" package on `conda-forge` which sets environment variables like `CC`, `CLFAGS`,... via an activation script.
  * `toolchain_LANGUAGE_PLATFORM` is `toolchain` + appropriate `run_exports`.
  * So, `toolchain_c_linux-64` has activation scripts and `run_exports` but does NOT ship with a compiler or glibc/libgcc sysroot. Instead it uses the system compilers, e.g., `CC` is set to `gcc` which is `/opt/rh/devtoolset-2/root/usr/bin/gcc` (unless `gcc` is installed to the `build`/`host` environments).
3. many recipes on conda-forge and Bioconda have been updated to use `{{ compiler(...) }}` so that they currently still use the old compilers (due to `conda-forge-pinning`), but can be ported to the newer compilers more easily once they are in use, i.e., once `conda-forge-pinning` is updated to make them available.
4. conda-forge is still working on the compiler transition and it'll need some more weeks, I'm afraid.
5. since Bioconda packages depend on conda-forge's ones, it makes sense for us to wait on them to avoid binary incompatibilities (mostly due to C++ STL stuff, I guess).
6. The compiler transition is long overdue.
7. A Docker image without devtoolset-2 will/can only be used *after* that transition of course, for the reason @daler points out :wink:.

If I missed anything or something is still unclear, please feel free to comment/ask anything!

**Comment by daler** [comment]
@mbargull very helpful to see this info all in one place, and it makes sense now. Thanks so much!
